### ISSUE TITLE
Unexpected character '`'

### ISSUE THREAD

**Issue by crobertsbmw** [jofftiquez/vue-stripe-checkout#1]
Everything seems to work great when running `npm run dev`, but I'm getting an error when I try to export for production by running `npm run build`:

```
ERROR in build.js from UglifyJs
Unexpected character '`' [./~/vue-stripe-checkout/index.js:1,0][build.js:16789,36]
```

This library looks awesome. Thanks.

**Comment by jofftiquez** [comment]
Hey @crobertsbmw it was due to the backticks ( ` ) I used. It's an ES6 feature, one way of dealing with this type of problem is to install es6 presets to your babel configuration. But I already updated the repo, please see the latest version in `npm`. Thanks!

**Comment by crobertsbmw** [comment]
Thank you very much, you kind sir.

**Comment by crobertsbmw** [comment]
Thanks for working with me on this.
I updated the package and now I am getting a similar but different error:
```ERROR in build.js from UglifyJs
Unexpected token: punc (() [./~/vue-stripe-checkout/index.js:6,0][build.js:16794,9]```

So I don't know the first thing about babel. But following the instructions [here](https://babeljs.io/docs/plugins/preset-env/), I ran 
`npm install babel-preset-env --save-dev`
and tried to modify my `.babelrc` and include `"presets": ["env"]`. But that didn't seem to change anything. I tried a bunch of different combinations with es2016, es6, es2015, but nothing seemed to change anything. I even tried removing all mention of presets from `.babelrc`, expecting that all sorts of things would break. But removing the presets line didn't seem to have any effect either; I could run `npm run dev`, and everything would work great, but if I ran `npm run build` I would get the same error about Uglify.

**Comment by jofftiquez** [comment]
Hi @crobertsbmw can I see your `.babelrc` please?

**Comment by jofftiquez** [comment]
@crobertsbmw I added a webpack build for the new update `0.0.4`. Kindly give me a feedback after checking it. Thank you. :) Sorry it took a while.

**Comment by crobertsbmw** [comment]
Here's my `.babelrc`:
{
  "presets": [ "env" ],
  "plugins": [
    "add-filehash",
    ["transform-imports", {
        "vuetify": {
            "transform": "vuetify/src/components/${member}"
        }
    }]
  ]
}

I had to uninstall and then reinstall it, but it's working. Thanks so much for all your help!

**Comment by jofftiquez** [comment]
@crobertsbmw You were missing the `stage-2` preset. Anyways, it's working now. :) Thanks for submitting the issue.
