### ISSUE TITLE
How to access stripeEmail and other attributes?

### ISSUE THREAD

**Issue by patrickbolle** [jofftiquez/vue-stripe-checkout#10]
I need to use stripeEmail to create a customer on my server, how do I access this after creating the charge with this plugin?

I can send the token, but what else can I grab + how?

Thanks!

**Comment by patrickbolle** [comment]
Nevermind! All that info is accessible within the token after creation.

Cheers.

**Comment by jofftiquez** [comment]
@patrickbolle Im glad you found it. Thanks for using this plugin.
