### ISSUE TITLE
Invalid stripe.redirectToCheckout parameter: items.0.sku is not an accepted parameter.

### ISSUE THREAD

**Issue by AlexanderWallner** [jofftiquez/vue-stripe-checkout#100]
Stripe does not accept items.0.sku parameter

sample 

<template>
  <base-section id="checkout">
    <stripe-checkout
      ref="checkoutRef"
      :pk="publishableKey"
      :items="items"
      :successUrl="successUrl"
      :cancelUrl="cancelUrl"
    >
      <template slot="checkout-button">
        <button @click="checkout">Checkout</button>
      </template>
    </stripe-checkout>
  </base-section>
</template>

<script>
  import { StripeCheckout } from 'vue-stripe-checkout'
  export default {
    components: {
      StripeCheckout,
    },
    data: () => ({
      loading: false,
      publishableKey: 'pk_test_XXXXX',
      items: [
        {
          sku: 'sku_H2aFkacRMvKufB',
          quantity: 1,
          name: 'Econom',
        },
      ],
      successUrl: 'http://waw-it.de',
      cancelUrl: 'http://waw-it.com',
    }),
    methods: {
      checkout () {
        this.$refs.checkoutRef.redirectToCheckout()
      },
    },
  }
</script>

**Comment by jofftiquez** [comment]
Please the code in your issue properly. Thanks.

**Comment by AlexanderWallner** [comment]
Hi there,
sorry, here is the zip with the component Checkout.vue 

[Checkout.vue.zip](https://github.com/jofftiquez/vue-stripe-checkout/files/4435714/Checkout.vue.zip)

Thanks,
Alex

**Comment by jofftiquez** [comment]
Hi @AlexanderWallner you don't have to send a zip file. Just use markdown code formatting. Thanks.

**Comment by asefcamel** [comment]
i got this error. what's wrong ? i used the same structure in the readme for the checkout component .. (index):1 Uncaught (in promise) IntegrationError: No such sku: sku_FdQKocNoVzznpJ

**Comment by asefcamel** [comment]
ok i found the issue. you have to make first an product in the dashboard. and you have to set your account details then it wil work.

**Comment by AlexanderWallner** [comment]
Hi there, the product is created in my stripe account. I will check again, thanks

**Comment by asefcamel** [comment]
make sure you pass the correct sku, stripe will auto generate one ..

**Comment by AlexanderWallner** [comment]
`<template>
  <base-section id="checkout">
    <stripe-checkout
      ref="checkoutRef"
      :pk="publishableKey"
      :items="items"
      :successUrl="successUrl"
      :cancelUrl="cancelUrl"
    >
      <template slot="checkout-button">
        <button @click="checkout">Checkout</button>
      </template>
    </stripe-checkout>
  </base-section>
</template>`
`<script>
  import { StripeCheckout } from 'vue-stripe-checkout'
  export default {
    components: {
      StripeCheckout,
    },
    data: () => ({
      loading: false,
      publishableKey: 'pk_test_JBPBCanEOKnppOEZscaNDBi400aLpoXutQ',
      items: [
        {
          sku: 'sku_H2aFkacRMvKufB',
          quantity: 1,
          name: 'Econom',
        },
      ],
      submitType: 'auto',
      successUrl: 'http://waw-it.de',
      cancelUrl: 'http://waw-it.com',
    }),
    methods: {
      checkout () {
        this.$refs.checkoutRef.redirectToCheckout()
      },
    },
  }
</script>`

In my example it is sku_H2aFkacRMvKufB

**Comment by asefcamel** [comment]
ok i think i found your issue it's the name i think.. just remove the name..

**Comment by AlexanderWallner** [comment]
I added the name because the stripe API answers that the name is needed

**Comment by jofftiquez** [comment]
Hello, did you find a solution @AlexanderWallner? Thanks @asefcamel for assisting. 

For future issues kindly use the proper mark down formatting. What you did is for single line code. Kindly refer to [this](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting).

**Comment by AlexanderWallner** [comment]
Thanks guys, yes, it works now without name in sku. Now I now how to markdown correctly)

**Comment by thedelk** [comment]
@AlexanderWallner Would you mind mentioning what you did to resolve your issue, in case others have the same problem?
