### ISSUE TITLE
Unclear as to how the token and charge are supposed to be used.

### ISSUE THREAD

**Issue by true-zero** [jofftiquez/vue-stripe-checkout#103]
**Is your feature request related to a problem? Please describe.**
Currently I'm having to sift through the Stripe documentation try and figure out how the token and charge variables shown in the example for Stripe Elements are supposed to be used and I'm still scratching my head trying to figure it out.

**Describe the solution you'd like**
Ideally an example of how you'd also process the payments, but at the minimum indication of how the two variables are supposed to be used.

**Comment by jofftiquez** [comment]
Hello @true-zero you are right. The token usage is currently not yet documented. I apologize. For the meantime, you can refer to [this](https://github.com/jofftiquez/vue-stripe-checkout/pull/93#issuecomment-612557500).

**Comment by jofftiquez** [comment]
Oh my bad. This is about the token and charge. I thought it was about sessions and checkout. Can you tell me what you have tried so far?

**Comment by jofftiquez** [comment]
See my Stripe Element example [here](https://github.com/jofftiquez/vue-stripe-checkout#vue-stripe-elements), in the `tokenCreated ` method.

For the record, the charging of the customer is all done in the backend. To do that, you just have to pass this payload to your backend:

```
{
  source: token.card, // the outpuf of the `tokenCreated` method from @token event.
  amount: this.amount, // the amount you want to charge the customer in cents. $100 is 1000
  description: this.description // optional description
}
```
Let me know if you still have problems. I'm closing this now.

**Comment by krebbi** [comment]
@true-zero You need to install https://github.com/stripe/stripe-php

in the "sendTokenToServer" method in your vue you have to send the token to your backend. Example with axios:

`tokenCreated (token) {
      this.token = token
      // for additional charge objects go to https://stripe.com/docs/api/charges/object
      
      this.sendTokenToServer(this.token, this.registered.id, this.workshop.price * 100, this.workshop.currency, this.registered.email)
    },

sendTokenToServer (stripetoken, id, amount, currency, email) {
      axios.post('/api/workshop_registrations/payment',
        {
          id: id,
          stripetoken: stripetoken,
          amount: amount,
          currency: currency,
          email: email
        }
      ).then(({ data }) => {
        console.log(data)
        if (data === 'Success') {
          this.done()
        }
      })
    },
    done () {
      this.$router.push({ name: 'event_thanks' })
    }`

and in your function in your payment controller:

`use Stripe\Stripe;
use Stripe\Customer;
use Stripe\Charge;


public function payment (Request $request) {
    		try {
				Stripe::setApiKey(env('STRIPE_SECRET_KEY'));

				$customer = Customer::create(array(
					'email' => $request->get('email'),
					'source' => $request->get('stripetoken')['id']
				));

				$charge = Charge::create(array(
					'customer' => $customer->id,
					'amount' => $request->get('amount'),
					'currency' => $request->get('currency')
				));

				// Store $charge somewhere in your DB or process it. 

				return 'Success';
			} catch (\Exception $ex) {
				return $ex->getMessage();
			}
	}`

and that's it.
