### ISSUE TITLE
An empty button being created by the example

### ISSUE THREAD

**Issue by true-zero** [jofftiquez/vue-stripe-checkout#105]
**Describe the bug**
An empty submit button being created under the Stripe elements.
![image](https://user-images.githubusercontent.com/46781337/79630609-b60ba180-814a-11ea-8a71-5c3ae17ce801.png)

**To Reproduce**
```
<stripe-elements ref="elementsRef" :pk="publicKey" @token="tokenCreated">
</stripe-elements>
```

**Expected behavior**
For there to be no empty submit button and for it look like this:
![image](https://user-images.githubusercontent.com/46781337/79630653-03880e80-814b-11ea-9821-f5eedb4eb16a.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 80

**Comment by jofftiquez** [comment]
Hello kindly ignore it for a while. I will deploy a new version to fix this in a few hours. I just have to finish my work. Thanks @true-zero

**Comment by true-zero** [comment]
@jofftiquez Any updates on this issue?

**Comment by jofftiquez** [comment]
Hello @true-zero checkout `v3.3.1`
