### ISSUE TITLE
Allow Locale to be passed on Stripe Elements

### ISSUE THREAD

**Issue by siba2893** [jofftiquez/vue-stripe-checkout#106]
**Is your feature request related to a problem? Please describe.**
Yes cause errors are coming out in English only.

**Describe the solution you'd like**
Be able to pass the locale to the vue-stripe-checkout and have it translated.

**Comment by jofftiquez** [comment]
Hello @siba2893 this feature hasn't been implemented yet. I will look into it. Thanks.

**Comment by jofftiquez** [comment]
Hello I uploaded a new version that includes [these new options](https://github.com/jofftiquez/vue-stripe-checkout#vue-stripe-elements). Check version `v3.3.0`

**Comment by siba2893** [comment]
Beautiful thanks for such a quick response.
