### ISSUE TITLE
Enhancement: Expose elements.create('card') options

### ISSUE THREAD

**Issue by siba2893** [jofftiquez/vue-stripe-checkout#107]
**Is your feature request related to a problem? Please describe.**
Please expose the options of the card element listed on stripe.js documentation so we can take decisions on how the elements behave. Example: Hide the Postal Code

**Describe the solution you'd like**
Merge cardElements hash with this hash:

```
props: {
   ...
   cardOptions: {
      type: Object,
      default: () => ({})
   }
}
```
```
const cardOpts = {...{ style: this.stripeStyle }, ...this.cardOptions, } 
this.elements.create('card', cardOpts);
```

**Comment by jofftiquez** [comment]
Thanks @siba2893 I'll look into this.

**Comment by siba2893** [comment]
Awesome :D Thanks for promptly respond!

**Comment by leep0o** [comment]
When do you plan to add this feature to the master branch?

**Comment by jofftiquez** [comment]
See #124
