### ISSUE TITLE
Collecting single stripe payment 

### ISSUE THREAD

**Issue by ajitgoel** [jofftiquez/vue-stripe-checkout#114]
I am working on collecting a single payment using the documentation at https://stripe.com/docs/payments/accept-a-payment. 
Based on my understanding, I should be able to use "Vue Stripe Elements" to "collect card details" and  then on click of the payment button to "submit the payment to Stripe".
When I "submit the payment to Stripe", I would pass the client secret I retrieved from the server above and the card details I collected using "Vue Stripe Elements". Is my understanding correct? 
I am asking as I am not sure I follow the tokenCreated, Submit, sendTokenToServer methods(shown in the github example) and how they would work for "collecting a single payment"?  
Also is the source code for the "elements demo" at  https://jofftiquez.github.io/vue-stripe-checkout/ shared somewhere? I would love to have a look.

**Comment by Meseeksivs** [comment]
https://github.com/jofftiquez/vue-stripe-checkout/blob/master/index.html <- The source code is already there.

**Comment by ajitgoel** [comment]
Thank you @Meseeksivs , I resolved the issue by integrating with stripe elements directly.
