### ISSUE TITLE
Unexpected token: name (d) 

### ISSUE THREAD

**Issue by ty7466** [jofftiquez/vue-stripe-checkout#115]
Receiving this error 
` ERROR in main.js from UglifyJs
    Unexpected token: name (d) [main.js:49280,1931]`

**To Reproduce**
Upgraded from legacy version to new version. Created a Stripe elements checkout process
It builds when I run a dev build but fails on npm run build for prod

Heres my babelrc

`{
  "presets": ["es2015", "stage-2"],
  "plugins": [
    "transform-runtime",
    "transform-async-to-generator"
  ],
  "comments": false
}
`

**Comment by inverite** [comment]
Also having this same issue.  All the way back to 1.2.6 which doesn't have StripeElements.  Any fix underway @jofftiquez ?

Thank you

**Comment by ty7466** [comment]
@inverite So what I had to do is switch from using webpack uglify to a different minifier. Since Uglify does support es2015 I think

**Comment by jofftiquez** [comment]
Hello all, apologies for the late reply, as you can see, I am very busy with my day job. I hope you understand. :( I'm more than happy to fix this issue. I just need the following information:

1. Version of vue cli that you guys are using
2. Babel config

Thank you.

@ty7466 @inverite

**Comment by jofftiquez** [comment]
If you guys are using vue-cli 3, it seems babel-loader is already ignoring all deps from node_modules upon transpilation. Will still wait for your feedback tho.

https://cli.vuejs.org/config/#transpiledependencies

**Comment by jofftiquez** [comment]
Hello all, I gave time to check this lately. You can ignore `vue-stripe-checkout` in your webpack config under UglifyJsPlugin configuration using `exclude` property.
