### ISSUE TITLE
The items parameter is no longer supported

### ISSUE THREAD

**Issue by ryoju-ohata** [jofftiquez/vue-stripe-checkout#117]
The line parameter has been changed to the lineItems in the redirectToCheckout.
We need to rewrite it to the lineItems.

https://stripe.com/docs/payments/checkout/migration#client-products

**Comment by jofftiquez** [comment]
Cool! Thanks for the heads up @ryoju-ohata I will keep this issue open. Are you planning to do a PR? Just let me know.

**Comment by ryoju-ohata** [comment]
Thanks @jofftiquez
I'm not familiar with this code, so I'm not planning to do a PR.

**Comment by jofftiquez** [comment]
I understand. Thanks. Will add this to my to-do list.
