### ISSUE TITLE
Research

### ISSUE THREAD

**Issue by jcalfee** [jofftiquez/vue-stripe-checkout#119]
Please do your research .. Of course Black Lives Matter, but BLM is a funding by billionaire George Sores and is designed from the ground up to trick good people into violence and therefore providing governments the justification they need to bring in more tyrannical abuse of freedom.  In other words, you think the police state is bad now, it will get worse if we sell out, take money, and listen to the media.  They will trick us with movements.

I'm not saying everyone in BLM is bad .. the opposite it true.  Mostly everyone is good.  However, the movement is funded and designed to trick people.  Trust me, it is working very well.  Do your homework. Research Research Research ..

Thank you,
jc

**Comment by jcalfee** [comment]
Sorry, was not trying to spam you .. I saw a BLM reference somewhere and was concerned I should have put that reference above.  Trying to get some food for thought out there, maybe tip the odds a bit.

**Comment by jofftiquez** [comment]
Thank you @jcalfee I'll do my part of the research. For the record, I don't think all cops are bad, or all black people are good. Both have their fair share of goodness or badness in them. I just hope that you understand that the campaign BLM does not only apply to that specific case with George Floyd. I get you, the man was a criminal, however what the cop did was clearly unconstitutional. Thank you for you time, and for keeping an open mind. Cheers mate.
