### ISSUE TITLE
How can the Style Object be used?

### ISSUE THREAD

**Issue by rajsinghUSA** [jofftiquez/vue-stripe-checkout#120]
Hi @jofftiquez , thank you for creating this useful Vue component.

I am wondering how `vue-stripe-elements` can be styled with the [Style Object](https://stripe.com/docs/js/appendix/style). Looking through the `/src` code, it didn't appear to accept any `style` prop, but some discussions in this repo's Issues section lead me to believe it is still possible.

Can you (or anyone) please clarify?

**Comment by jofftiquez** [comment]
Hello @ragesh-kannan I added a new `prop` called `styleObject` in `v3.5.5`. This will override the default style provided by this plugin.
