### ISSUE TITLE
How to create discrete inputs for credit card information (like in screenshot)

### ISSUE THREAD

**Issue by rajsinghUSA** [jofftiquez/vue-stripe-checkout#121]
This screenshot displays a credit card input form with individual inputs for the card information (CC#, expiration, CVV) and also the name, country, and email:

![image](https://user-images.githubusercontent.com/17286177/85618173-65269680-b62e-11ea-96c5-99b7cf6bcbd8.png)

Based on the [Vue Stripe Elements example][3] shown in the GitHub README.md, my *single-file Vue component* currently creates a single input for all the credit card information. It looks like this:

[![enter image description here][4]][4]

And this is the code that created it:
```js
<template>
  <div>
    <StripeElements
      ref="elementsRef"
      :pk="publishableKey"
      :amount="amount"
      @token="tokenCreated"
      @loading="loading = $event"
    >
    </StripeElements>
    <button @click="submit">Pay ${{ amount / 100 }}</button>
  </div>
</template>

<script>
import { StripeElements } from "vue-stripe-checkout";

export default {
  components: {
    StripeElements
  },
  data: () => ({
    loading: false,
    amount: 1000,
    publishableKey: process.env.VUE_APP_PUBLISHABLE_KEY,
    token: null,
    charge: null
  }),
  methods: {
    submit() {
      this.$refs.elementsRef.submit();
    },
    tokenCreated(token) {
      this.token = token;
      // for additional charge objects go to https://stripe.com/docs/api/charges/object
      this.charge = {
        source: token.id,
        amount: this.amount, // the amount you want to charge the customer in cents. $100 is 1000 (it is strongly recommended you use a product id and quantity and get calculate this on the backend to avoid people manipulating the cost)
        description: this.description // optional description that will show up on stripe when looking at payments
      }
      this.sendTokenToServer(this.charge);
    },
    sendTokenToServer(charge) {
      // Send to charge to your backend server to be processed
      // Documentation here: https://stripe.com/docs/api/charges/create
      console.log(charge)
    }
  }
};
</script>

<style lang="scss" scoped></style>
```

However, after scouring its documentation, limited examples ([here][5] and [its source code][6]), and Issues section, I am unclear on how a credit card input form with individual inputs for the card information (CC#, expiration, CVV) and also the name, country, and email can be created.

I am hoping someone with experience with Stripe might be able to shed some light. Thank you.

  [1]: https://github.com/jofftiquez/vue-stripe-checkout#vue-stripe-checkout
  [2]: https://i.stack.imgur.com/RX6vL.png
  [3]: https://github.com/jofftiquez/vue-stripe-checkout#vue-stripe-elements
  [4]: https://i.stack.imgur.com/JAVSK.png
  [5]: https://jofftiquez.github.io/vue-stripe-checkout/
  [6]: https://github.com/jofftiquez/vue-stripe-checkout/blob/master/index.html

**Comment by jofftiquez** [comment]
Hello @rajsinghUSA thanks for this. You're probably looking for something [like this](https://jsfiddle.net/ywain/o2n3js2r/) right? The stripe element instance has a method called `.create(name?, options?)` that lets you create an element and mount it using the `.mount(id)` method. Creating dynamic elements  is not yet supported in this project. I can do this but I can't promise anything, as I am so busy right now, I hope you understand.

You can still achieve it by modifying [the code](https://github.com/jofftiquez/vue-stripe-checkout/blob/master/src/Elements.vue#L84) of the Element.vue component. 

Around line 84, you can create and mount separate elements such as `cc number`, `expiry date`, `cvc`, etc. instead of just the `card` element.

**Comment by jofftiquez** [comment]
See #124
