### ISSUE TITLE
Cannot read property 'install' of undefined

### ISSUE THREAD

**Issue by vivek-kachhadiya13** [jofftiquez/vue-stripe-checkout#122]
**Uncaught TypeError: Cannot read property 'install' of undefined**
  To Reproduce Steps to reproduce the behavior:

import VueStripeCheckout from 'vue-stripe-checkout'
console.log(VueStripeCheckout) --> VueStripeCheckout is undefined
Vue.use(VueStripeCheckout, options);

"vue-stripe-checkout": "^3.3.1"
"vue": "^2.6.11"

**Comment by jofftiquez** [comment]
Thanks for sending an issue, see duplicate #98.
