### ISSUE TITLE
It looks like Stripe.js was loaded more than one time. Please only load it once per page.

### ISSUE THREAD

**Issue by MohawkMan** [jofftiquez/vue-stripe-checkout#123]
When using in a SPA every time you navigate to the page with the component it loads stripe.js

![image](https://user-images.githubusercontent.com/9752771/87253610-75fa4900-c431-11ea-816b-8fa071fbf85d.png)

Can you simply put an id on the script tag and look for the script before appending it?

**Comment by MohawkMan** [comment]
P.S. if I can get to it today I will try to submit a PR

**Comment by jofftiquez** [comment]
Hello @MohawkMan let me know if you come up with a solution. Otherwise I'll add this to my to do list. Thank you!
