### ISSUE TITLE
Not redirecting to checkout page

### ISSUE THREAD

**Issue by waqas61** [jofftiquez/vue-stripe-checkout#125]
**On click checkout button not redirecting to stripe checkout page**

**To Reproduce**
Using Vue Stripe Checkout.
error TypeError: Cannot read property 'length' of null

**Desktop (please complete the following information):**
 - OS: [Window]
 - Browser [chrome]
 - Version [83]

**Comment by jofftiquez** [comment]
Hello @waqas61 can you provide a screenshot.

**Comment by waqas61** [comment]
> Hello @waqas61 can you provide a screenshot.

Thanks for your time !

Screen Shot URL

https://prnt.sc/thwex9

**Comment by jofftiquez** [comment]
Hello @waqas61 version `v3.5.6` is being uploaded now via CI/CD. You can upgrade your vue-stripe-checkout to the latest version in a few minutes. Please let me know if the fix works, thank you.

**Comment by waqas61** [comment]
Hello @jofftiquez now there is an other error am facing 
`IntegrationError: Invalid value for stripe.redirectToCheckout: clientReferenceId should be a string. You specified: null.`

**Comment by jofftiquez** [comment]
May I see you configuration?

**Comment by waqas61** [comment]
> May I see you configuration?

Yes

`<template>
  <stripe-checkout
    ref="checkoutRef"
    :pk="publishableKey"
    :items="items"
    :successUrl="successUrl"
    :cancelUrl="cancelUrl"
  >
    <template slot="checkout-button">
      <button @click="checkout">Shut up and take my money!</button>
    </template>
  </stripe-checkout>
</template>

<script>
import { StripeCheckout } from 'vue-stripe-checkout';

export default {
  components: {
    StripeCheckout
  },

  data: () => ({
    loading: false,
    publishableKey: 'pk_test_80cpuI7dZJ4h4Mfx4q0xUpiV006StsFDgm',
    items: [
      {
        sku: 'sku_FdQKocNoVzznpJ', 
        quantity: 1
      }
    ],
    successUrl: 'http://www.google.com',
    cancelUrl: 'http://www.google.com',
  }),
  methods: {
    checkout () {
      this.$refs.checkoutRef.redirectToCheckout();
    }
  }
}
</script>`

**Comment by waqas61** [comment]
> May I see you configuration?

`
<template>
  <stripe-checkout
    ref="checkoutRef"
    :pk="publishableKey"
    :items="items"
    :successUrl="successUrl"
    :cancelUrl="cancelUrl"
  >
    <template slot="checkout-button">
      <button @click="checkout">Shut up and take my money!</button>
    </template>
  </stripe-checkout>
</template>

<script>
import { StripeCheckout } from 'vue-stripe-checkout';

export default {
  components: {
    StripeCheckout
  },

  data: () => ({
    loading: false,
    publishableKey: 'pk_test_80cpuI7dZJ4h4Mfx4q0xUpiV006StsFDgm',
    items: [
      {
        sku: 'sku_FdQKocNoVzznpJ', 
        quantity: 1
      }
    ],
    successUrl: 'http://www.google.com',
    cancelUrl: 'http://www.google.com',
  }),
  methods: {
    checkout () {
      this.$refs.checkoutRef.redirectToCheckout();
    }
  }
}
</script>
`

**Comment by waqas61** [comment]
> May I see you configuration?

`
<template>
  <stripe-checkout  ref="checkoutRef"  :pk="publishableKey" :items="items" :successUrl="successUrl"  :cancelUrl="cancelUrl" >
    <template slot="checkout-button">
      <button @click="checkout">Shut up and take my money!</button>
    </template>
  </stripe-checkout>
</template>
`

> import { StripeCheckout } from 'vue-stripe-checkout';

export default {
  components: {  StripeCheckout  },

  data: () => ({
    loading: false,
    publishableKey: 'pk_test_80cpuI7dZJ4h4Mfx4q0xUpiV006StsFDgm',
    items: [  {sku: 'sku_FdQKocNoVzznpJ',  quantity: 1 }  ],
    successUrl: 'http://www.google.com',
    cancelUrl: 'http://www.google.com',
  }),
  methods: {
    checkout () {
      this.$refs.checkoutRef.redirectToCheckout();
    }
  }
}

**Comment by jofftiquez** [comment]
Hello I pushed another fix, would you mind trying again? Thanks.

**Comment by waqas61** [comment]
> Hello I pushed another fix, would you mind trying again? Thanks.

Sure. Let me try it with

**Comment by waqas61** [comment]
@jofftiquez Thanks its working now

**Comment by jofftiquez** [comment]
Cool!
