### ISSUE TITLE
v3:1 Uncaught (in promise) IntegrationError: SKUs for Checkout require a `name` attribute.

### ISSUE THREAD

**Issue by JaLe29** [jofftiquez/vue-stripe-checkout#130]
**Describe the bug**
I am getting an error for demo code 

`v3:1 Uncaught (in promise) IntegrationError: SKUs for Checkout require a `name` attribute.`

**To Reproduce**
Use this demo code with your publishableKey and sku and with some demo urls.
```
<template>
  <stripe-checkout
    ref="checkoutRef"
    :pk="publishableKey"
    :items="items"
    :successUrl="successUrl"
    :cancelUrl="cancelUrl"
  >
    <template slot="checkout-button">
      <button @click="checkout">Shut up and take my money!</button>
    </template>
  </stripe-checkout>
</template>

<script>
import { StripeCheckout } from 'vue-stripe-checkout';
export default {
  components: {
    StripeCheckout
  },
  data: () => ({
    loading: false,
    publishableKey: process.env.PUBLISHABLE_KEY,
    items: [
      {
        sku: 'sku_FdQKocNoVzznpJ', 
        quantity: 1
      }
    ],
    successUrl: 'your-success-url',
    cancelUrl: 'your-cancel-url',
  }),
  methods: {
    checkout () {
      this.$refs.checkoutRef.redirectToCheckout();
    }
  }
}
</script>
```

**Expected behavior**
Should redirect to payment page

**Comment by Deph0** [comment]
Hi, had the exact same problem, the product needs to have the attributes used in the SKU, but without values.

using Stripe Product API, you create a product with name attribute by using `&attributes[]=name`
and then you can use the SKU api to set that attribute, using `&attributes[name]=<your name here>`

**Comment by jofftiquez** [comment]
Hello thank you for submitting this. I will look into it. Sorry I can't do it ASAP but I will try my best. Maybe sometime this weekend (PHT).

**Comment by Deph0** [comment]
It's a problem with Stripe / Stripes API, not the component.

**Comment by jofftiquez** [comment]
Is there any updates on this @JaLe29 

Try using `lineItems` instead of `items`. Closing for now, kindly reopen or create a new issue if the problem still persist. Thanks.
