### ISSUE TITLE
Not allowing me to do client-only integration with product or price IDs

### ISSUE THREAD

**Issue by aligajani** [jofftiquez/vue-stripe-checkout#131]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jofftiquez** [comment]
Hello @aligajani I created the issue template for a reason, to help you and me in resolving issues like these. Please fill-out the template, and give more precise description of the issue, examples of what you've done, and error message/screenshots if there are any.
