### ISSUE TITLE
Vuejs Stripe not working correctly

### ISSUE THREAD

**Issue by jamols09** [jofftiquez/vue-stripe-checkout#132]
![image](https://user-images.githubusercontent.com/20100579/90796686-341ec580-e342-11ea-87c1-683a7b92c122.png)

I have installed Stripe on my Vue  and tried to implement the code based on this documentation and created an account and filled up the publishable key.  Looks simple and easy but upon trying to view it I only see an old button without any functionality. Have I missed something on my steps? 

This is my [source ](https://github.com/jofftiquez/vue-stripe-checkout#install) of implementation

**Comment by jofftiquez** [comment]
Hello @jamols09 what happens when you click the button? Are there any errors? Thanks.

**Comment by jamols09** [comment]
Hello @jofftiquez  apologies for not including the error. Here it is:
```v3:1 Uncaught (in promise) IntegrationError: No such sku: 'sku_FdQKocNoVzznpJ'```

**Comment by jofftiquez** [comment]
Hello @jamols09 it seems you supplied a non existing `sku`. You can create a new one in your dashboard and use it.

**Comment by jamols09** [comment]
Good day, @jofftiquez  I asked from the stripe support how to recover the SKU's but they said the product SKU's are no longer supported. So how can I create a Checkout module from Stripe?
![image](https://user-images.githubusercontent.com/20100579/90854483-a083de00-e3af-11ea-9974-fa088783faa1.png)

**Comment by jamols09** [comment]
@jofftiquez although they have provided me a solution but its different. Whenever I create a product, I can generate a code *but* after enabling this *[Checkout client-only integration](https://dashboard.stripe.com/settings/checkout)*.  but the problem is that this one does not use Vuejs.

**Comment by thesolyd** [comment]
I changed the sku to price like this.
```
{
       price: 'price_1HLtmjAoGRu8b6VonG09zbmv',
       quantity: 1
     }
```

But that gives error:

> IntegrationError: Invalid stripe.redirectToCheckout parameter: items.0.price is not an accepted parameter.

**Comment by thesolyd** [comment]
Instead of items, you have to pass lineItems and replace price with sku. It works.

**Comment by ielvisd** [comment]
> Instead of items, you have to pass lineItems and replace price with sku. It works.

Thanks @thesolyd! I ran into this as well and got it to work after reading your comment. No sku required. 

```
<stripe-checkout
    ref="checkoutRef"
    :pk="publishableKey"
    :lineItems="lineItems"
    mode="payment"
    :successUrl="successUrl"
    :cancelUrl="cancelUrl"
>

...

lineItems: 
       [{
        price: "YOUR_PRICE_ID",
        quantity: 1
      }],
```

**Comment by jofftiquez** [comment]
Hello all, reading your comments I'm not yet sure if there are some changes in the stripe sdk that not yet integrated in this plugin. I will review the documentations and will do necessary adjustments if needed. Thanks for working together to solve this.
