### ISSUE TITLE
Support additional fields

### ISSUE THREAD

**Issue by oldirty91** [jofftiquez/vue-stripe-checkout#134]
It appears that Stripe allows for additional fields that arent exposed through the package:

- client_reference_id
- customer
- subscription_data (coupons)

Seems like adding the props to the componet and passing them on to the stripe.redirectToCheckout() call would be pretty straightforward.

**Comment by jofftiquez** [comment]
Hello thanks, I will add these if needed. Let me just double check as soon as I become vacant. Thanks.

**Comment by jofftiquez** [comment]
I just checked some of the props you listed are already available in the package:

- [clientReferenceId](https://github.com/jofftiquez/vue-stripe-checkout/blob/620bccd5e46231193d386003243cfaf908616b2a/src/Checkout.vue#L49)
- [customerEmail](https://github.com/jofftiquez/vue-stripe-checkout/blob/620bccd5e46231193d386003243cfaf908616b2a/src/Checkout.vue#L52) <- IDK if this would suffice?
- subscriptionData - would you mind sending me the link to the docs for this prop?

Thanks @oldirty91

**Comment by jofftiquez** [comment]
I just want to remind you that all of the props in this package are based in this checkout options available on their docs https://stripe.com/docs/js/checkout/redirect_to_checkout#stripe_checkout_redirect_to_checkout-options I don't see anything about `subription_data`. Maybe you wanna check the lineItems, and the mode property.

**Comment by AZhiKai** [comment]
Hi @jofftiquez, thanks for creating this library. 

I was wondering if you could also look into allowing users to disable certain fields like zip code (I encountered this for my business use case).

In `Elements.vue`, 

```
      this.card = this.elements.create('card', { style: this.style });
```

Zip code can be disabled by passing `hidePostalCode: true,` as such

```
      this.card = this.elements.create('card', hidePostalCode: true, { style: this.style });
```

**Comment by jofftiquez** [comment]
> Hi @jofftiquez, thanks for creating this library.
> 
> I was wondering if you could also look into allowing users to disable certain fields like zip code (I encountered this for my business use case).
> 
> In `Elements.vue`,
> 
> ```
>       this.card = this.elements.create('card', { style: this.style });
> ```
> 
> Zip code can be disabled by passing `hidePostalCode: true,` as such
> 
> ```
>       this.card = this.elements.create('card', hidePostalCode: true, { style: this.style });
> ```
> 
> Perhaps prop `hideZipCode` should work? :)

Hello @AZhiKai thank you for submitting this. May I request to you to create a separate issue for this? Thanks. I will be closing this thread due to inactivity of the poster.
