### ISSUE TITLE
How to use price key with it's value

### ISSUE THREAD

**Issue by dekts** [jofftiquez/vue-stripe-checkout#137]
In the latest stripe API they are providing the option to create the product.

https://stripe.com/docs/api/plans/create

when we have created the product at that time we have the price key and value for product.

So can we use it like

```
items: [
  {
    "price": "price_1HRuB1CtXJ5xUkxFDXUiPcV6",
    "quantity": 1
  }
]
```

**Comment by jofftiquez** [comment]
I'm not sure if there's a `price` field for the items/lineItems. Check the options [here](https://stripe.com/docs/js#stripe_checkout_redirect_to_checkout-options-items-sku,%20plan) :)

**Comment by haivp3010** [comment]
@dekts I got price working by using `lineItems` instead of `items`. You would also need `mode="subscription"` and enable **Checkout client-only integration** on Stripe dashboard.
The docs doesn't seem to be updated with the new API yet, but it does work.

**Comment by jofftiquez** [comment]
Thank you @dekts I didn't realize that wasn't in my docs. I will add this to the upcoming docs update. Kindly [check this out](https://randomcodetips.com/vue-stripe-checkout-whats-next/).
