### ISSUE TITLE
[DEMO] I have integrated vue-stripe-checkout into a AWS Quickstart for creating a SaaS with Stripe 

### ISSUE THREAD

**Issue by sk-t3ch** [jofftiquez/vue-stripe-checkout#138]
(I don't know where to put this)
Firstly, thanks to the contributors!
Secondly, I have created a live demo of using this project in a SaaS https://saas-app.t3chflicks.org/ and the code can be found here https://github.com/sk-t3ch/AWS_Stripe-SaaS-quickstart. I also wrote a couple of blog posts about it [pt. 1](https://medium.com/@t3chflicks/users-only-quickstart-for-creating-a-saas-pt-1-user-management-3ca7e3332565)  and [pt. 2](https://medium.com/@t3chflicks/pay-me-quickstart-for-creating-a-saas-pt-2-stripe-payments-44bc4bb8388e).

I do not share these for pure self promotion. I am just trying to share resources I wish I had when starting.

I hope this project will accept showing this as another example of a live demo :)

**Comment by jofftiquez** [comment]
Hello @sk-t3ch Sure, thanks for using my work. :) 

>  I am just trying to share resources I wish I had when starting.

I totally get this, this is the reason why I started https://randomcodetips.com I wish I had these kinds of easy to understand guide when I was just starting.

Imma try to find a spot for these kinds of example in the docs or in my blog. For more of stuff like this, you can reach me thru email, or on twitter [@jrtiquez](https://twitter.com/jrtiquez) Thanks.
