### ISSUE TITLE
Allow promotion codes / coupons

### ISSUE THREAD

**Issue by fguespe** [jofftiquez/vue-stripe-checkout#139]
Hi! I cant send this to allow coupons in subscriptions

allow_promotion_codes:true

**Comment by jofftiquez** [comment]
Hello @fguespe can you send me here the link to the documentation about `allow_promotion_codes`? Thanks :)

**Comment by jofftiquez** [comment]
Here's the documentation [Coupon](https://stripe.com/docs/api/coupons). If you want to use it on checkout, you can use is via [Sessions](https://stripe.com/docs/api/checkout/sessions/create#create_checkout_session-subscription_data-coupon).

**Comment by santoshag** [comment]
+1 to support `allow_promotion_codes` in Checkout

**Comment by javimendezona** [comment]
Is there any chance we can get this option added to the component? It would be nice and I think a lot of people would benefit from having promo codes for subscriptions.

**Comment by deepshar78** [comment]
I am wondering who will use vue-stripe if coupon codes are not supported. This is a very basic and mandatory feature. Can the vue-stripe team help?

**Comment by jofftiquez** [comment]
> Is there any chance we can get this option added to the component? It would be nice and I think a lot of people would benefit from having promo codes for subscriptions.

> I am wondering who will use vue-stripe if coupon codes are not supported. This is a very basic and mandatory feature. Can the vue-stripe team help?

This is the whole list of options for the `.redirectToCheckout` method for the checkout functionality. There are no option here to add promo code. As I have mention on my comment above, you need to use the [Coupons](https://stripe.com/docs/api/coupons), [Promo Codes](https://stripe.com/docs/api/promotion_codes), or [Discounts](https://stripe.com/docs/api/discounts) APIs to create the coupon and create a [Session](https://stripe.com/docs/api/checkout/sessions/object) with [`allow_promotion_codes`](https://stripe.com/docs/api/checkout/sessions/object#checkout_session_object-allow_promotion_codes) enabled.

This is something you can just simply pass as an option to the checkout method. I can't add something that doesn't exist. 

@javimendezona @deepshar78
