### ISSUE TITLE
lineItems format?

### ISSUE THREAD

**Issue by Jesus82** [jofftiquez/vue-stripe-checkout#141]
Hi, my aim is to create one-time payments as described [here](https://stripe.com/docs/payments/accept-a-payment?integration=elements) and [here](https://stripe.com/docs/api/checkout/sessions/create#create_checkout_session-line_items) (I do not want to create each product in Stripe as I have lots of references that are constantly changing)

My StripeCheckout component setup is:
```
    <StripeCheckout
          ref="elementsRef"
          :pk="pk"
          :lineItems="lineItems"
          :mode="'payment'"
          :successUrl="successUrl"
          :cancelUrl="cancelUrl"
        >
    </StripeCheckout>
    <template slot="checkout-button">
        <button @click="checkout">Shut up and take my money!</button>
    </template>
```

and in my data I have the following (I'm using Nuxt)

```
data: function() {
    this.pk = process.env.STRIPE_PK;
    return {
      checkoutDone: false,
      lineItems: [{
        price_data: {
          currency: 'eur',
          product_data: {
            name: 'myProduct',
          },
          unit_amount_decimal: 1500,
        },
        quantity: 1,
      }],
      loading: false,
      successUrl: 'http://localhost:3000',
      cancelUrl: 'http://localhost:3000'
    },
    methods: {
      checkout () {
        this.$refs.checkoutRef.redirectToCheckout();
      }
    }
```

When I click on the checkout button, I have this error in the console
`Invalid stripe.redirectToCheckout parameter: lineItems.0.price_data is not an accepted parameter.`
I have been checking the docs and I cannot find out why the lineItems object is rejected. Any hint would be very welcome.

Cheers and thanks for this module!

**Comment by jofftiquez** [comment]
Hello @Jesus82 the `lineItems` payload that you are using is the one meant for sessions which is done in the backend. You should check [this one](https://stripe.com/docs/js/checkout/redirect_to_checkout#stripe_checkout_redirect_to_checkout-options-lineItems), notice that it only has 2 properties, `price` and `quantity`. The one you're using, [this one](https://stripe.com/docs/api/checkout/sessions/create#create_checkout_session-line_items). What you can do is create a session in the backend. It will give you a "session id", use that session id here in vue-stripe-checkout, like [this one on the documentation](https://github.com/jofftiquez/vue-stripe-checkout#stripe-sessions).

**Comment by Jesus82** [comment]
Hi @jofftiquez, thanks for your reply. My problem is that with that I would like to pass a price to checkout, not a priceID (as described [here](https://stripe.com/docs/js/checkout/redirect_to_checkout#stripe_checkout_redirect_to_checkout-options-lineItems). The reason is that I don't want to create products in checkout as I sell craft beer and my references are constantly changing.

Is there any possibility of passing the prices without having to create them previously in Stripe? Thanks in advance

**Comment by jofftiquez** [comment]
If you intend to charge arbitrary amount to your customer you are probably looking for the [Charge](https://stripe.com/docs/api/charges/create) API. I haven't implemented this in the past but for my understanding this is how it should be:

1. Capture the "source" (the credit card of the customer) using payment intent. 
2. Pass the amount and the source to your backend to create a new Charge object.

You can also do this using Stripe Elements. May I know what's blocking you?
