### ISSUE TITLE
Get Stripe Checkout SessionId for Subscription before redirect?

### ISSUE THREAD

**Issue by hkdb** [jofftiquez/vue-stripe-checkout#142]
Thanks for making vue-stripe-checkout which made my life so much easier! Do you have any advice on what might be the best way to record the sessionId before the redirect when using Stripe Checkout? I am looking to record the session id so I can automatically upgrade/downgrade the subscription price when the customer chooses to upgrade/downgrade. I am also looking to run a cronjob that will check status of the subscription so I can make changes to accounts accordingly. I am also open to other suggestions if I am thinking about this all wrong. Thanks!

**Comment by hkdb** [comment]
Or to be clear, my end goal is that after successful payment, I will record the subscription id and work off of that.... Thanks!

**Comment by jofftiquez** [comment]
Hello @hkdb few points:

- Sessions are for one-time use only. Once the session has been used for, say, creating a subscription you cannot re-use it anymore.
- You can actually create a subscription without using sessions, you can just create Products with recurring Plans in your stripe dashboard
- To upgrade or downgrade your customers subscription, you need to use the Subscriptions/Plans API (I think). I'm not sure if you can use Checkout directly with this.
- You don't need cronjob to interact with user's subscription status, you can use Stripe's Webhook to interact with certain events like, e.g. "subscription expired".

**Comment by jofftiquez** [comment]
> Or to be clear, my end goal is that after successful payment, I will record the subscription id and work off of that.... I guess my next option is to make a webhook and just listen to successful subscriptions and update the db that way. Thanks!

That's it :)

**Comment by hkdb** [comment]
Thanks for the feedback! I was sort of looking for a secure/safe/simple way to do client only integration which I guess didn't really make sense. It made even less sense after I built the webhooks and found how easy it was.... ;) Thanks again!

**Comment by jofftiquez** [comment]
Happy to help @hkdb if you need help again with stripe just create an issue here just label it with "question". :)
