### ISSUE TITLE
Have any plans on allowing us to pass metadata

### ISSUE THREAD

**Issue by lucasctd** [jofftiquez/vue-stripe-checkout#143]
Do you guys have any plans to add a metadata property to the checkout component so we can pass metadata through the payment cycle?

For reference:
https://stripe.com/docs/api/checkout/sessions/create#create_checkout_session-metadata

Thanks in advance.

**Comment by jofftiquez** [comment]
Hello @lucasctd I can add this.

**Comment by lucasctd** [comment]
Thank you!

**Comment by jofftiquez** [comment]
Hello @lucasctd apologies, I won't be able to do this until Oct 17. 2020, PHT. I am still busy with my work.

**Comment by lucasctd** [comment]
Okay, no problem.

**Comment by jofftiquez** [comment]
Hello @lucasctd looking back at this, I didn't realize you were referring the `metadata` for `Sessions`. There are no metadata property for the checkout options [see](https://stripe.com/docs/js/checkout/redirect_to_checkout#stripe_checkout_redirect_to_checkout-options).

For your specific use case, what you can do is to create a new `Session` object with metadata property included in your backend. Then use that session's id in your checkout process on client side, [see](https://stripe.com/docs/js/checkout/redirect_to_checkout#stripe_checkout_redirect_to_checkout-options-sessionId).

For this plugin you only have to pass the `session-id` property together with your `publishable-key` like so:

```html
<vue-stripe-checkout
  pk="pk_test_..."
  ref="sessionRef"
  session-id="your-session-id-from-backend"
>
  //- button here
</vue-stripe-checkout>
```
