### ISSUE TITLE
Processing a order

### ISSUE THREAD

**Issue by robov** [jofftiquez/vue-stripe-checkout#147]
how can I process the order in my laravel backend ?
Is there a return or a callback from stripe somewhere that I am missing

**Comment by robov** [comment]
Ok, after reading the closed issues I think I have to add a webhook.
Maybe an idea to add a little section to the docs explaining that one needs to create a webhook in order to postprocess the order

**Comment by jofftiquez** [comment]
Hello @robov yes, webhook is the answer. Thanks for the suggestion, I will also add that to the upcoming docs. Thanks.
