### ISSUE TITLE
Unable to override key in this.$checkout.open()

### ISSUE THREAD

**Issue by reganjohnson** [jofftiquez/vue-stripe-checkout#19]
When I am trying to override the key, as hinted at in your documentation, it is loading in the Stripe JS library with an API error 

> "Stripe Checkout can't communicate with our payment processor because the API key is invalid. Please contact the website owner or support@stripe.com."

However, when I put the key in the stripeCheckoutOptions in app.js, it will load as intended.

In my `app.js`

```
const stripeCheckoutOptions = {
    key: 'placeholder-key-data',
    image: 'https://via.placeholder.com/100x100',
    locale: 'auto',
    currency: 'PHP',
    billingAddress: true,
    panelLabel: 'Purchase {{amount}}'
};
window.Vue.use(VueStripeCheckout, stripeCheckoutOptions);
```

And in my `component.vue`

```
export default {
        methods: {
            checkout() {
                this.$checkout.open({
                    key: 'pk_test_jHADJs8d9alkjhddhjks',
                    name: 'Shut up and take my money!',
                    currency: 'USD',
                    amount: 99999,
                    token: (token) => {
                        //
                    }
                });
            }
        },
    }
```

**Comment by jofftiquez** [comment]
Hello @reganjohnson I will investigate this. Thanks!

**Comment by rocchidavide** [comment]
Any news about this bug?

**Comment by jofftiquez** [comment]
Hello @reganjohnson kindly upgrade to v1.1.0. Thanks.
