### ISSUE TITLE
Calling Vue Code from within Token Callback

### ISSUE THREAD

**Issue by crobertsbmw** [jofftiquez/vue-stripe-checkout#2]
This probably isn't an issue with the checkout, but probably just me not knowing what I am doing. I am having trouble calling any other methods inside the `token()` callback:

```
export default {
  data () {
    return {
      email: '',
      ...
    }
  },
  methods: {
    submit(token){
        console.log("submit data to server");
        ....
    },
    checkout () {
      this.$checkout.open({
        name: 'Widgets',
        currency: 'USD',
        amount: 300,
        token(token) {
          console.log(token)
          this.submit(token)
        } 
      });
    }
  }
}
```
I am getting a `Uncaught TypeError: this.submit is not a function`. I've tried some other variations of calling submit(), this.submit, this.$submit, and it's not working. I'm assuming it has something to do with context?

**Comment by wesratcliff** [comment]
Give this a shot with an anonymous function...

```
export default {
  data () {
    return {
      email: '',
      ...
    }
  },
  methods: {
    submit(token){
        console.log("submit data to server");
        ....
    },
    checkout () {
      this.$checkout.open({
        name: 'Widgets',
        currency: 'USD',
        amount: 300,
        token: (token) => {
          console.log(token)
          this.submit(token)
        } 
      });
    }
  }
}
```

**Comment by jofftiquez** [comment]
Hello @crobertsbmw, @wesratcliff  was right. You are experiencing a context issue. The problem is that the context of `Vue` or `this` is not accessible inside the `token(token) {...}` because it has it's own execution context. You can solve this by using arrow function like what @wesratcliff did. `token: (token) => {...}`

**Comment by jofftiquez** [comment]
I probably should update the sample code. Thanks guys.

**Comment by crobertsbmw** [comment]
Thanks, guys. I found another way to make it work although it feels sinful and wrong:

```
let a = this.submit
this.$checkout.open({
          name: 'Widgets',
          currency: 'USD',
          amount: 300,
          token(token) {
            a(token.id)
          } 
});
```
Using the arrow syntax is obviously the right way to do it. Thanks again.

**Comment by jofftiquez** [comment]
@crobertsbmw Alternatively you can also do : 
```
var that = this;
this.$checkout.open({
  name: 'Widgets',
  currency: 'USD',
  amount: 300,
  token(token) {
    that.submit(token.id);
  } 
});
```
It's just a matter of handling the context really. :)
