### ISSUE TITLE
Make Amount Field Reactive

### ISSUE THREAD

**Issue by ogomaemmanuel** [jofftiquez/vue-stripe-checkout#21]
The amount field on the checkout is currently not reactive, any changes made on the vue instance are not reflecting on checkout component

**Comment by jofftiquez** [comment]
@ogomaemmanuel  thanks for this. I'll see what I can do.

**Comment by jofftiquez** [comment]
Hi @ogomaemmanuel @matthew-inamdar Kindly update to `v1.1.0` Thanks! And sorry for the delayed action.
