### ISSUE TITLE
Can I add more fields to card

### ISSUE THREAD

**Issue by Lahori-Jawan** [jofftiquez/vue-stripe-checkout#23]
This [doc](https://stripe.com/docs/checkout#integration-simple-parameters) shows additional parameters that are also passed as part of token but I don't see how to use them. I want to ask user to fill in their name for example so I could register them at the same time instead ask them again for registration. Like the image: 
![stripe](https://user-images.githubusercontent.com/7579344/48552185-9b038500-e8f9-11e8-932e-c7af7df65ad0.png)

**Comment by jofftiquez** [comment]
Hello @Lahori-Jawan in the [Stripe Docs](https://stripe.com/docs/checkout#integration-simple-options) you can see that there is a `billing_name` option available. You can check it out.

```
{
  // Billing name and address
  "billing_name": "Stripe",
  "billing_address_country": "United States",
  "billing_address_zip": "94111",
  "billing_address_state": "CA",
  "billing_address_line1": "1234 Main Street",
  "billing_address_city": "San Francisco",
  "billing_address_country_code": "US",

  // Shipping name and address
  "shipping_name": "Stripe",
  "shipping_address_country": "United States",
  "shipping_address_zip": "94111",
  "shipping_address_state": "CA",
  "shipping_address_line1": "1234 Main Street",
  "shipping_address_city": "San Francisco",
  "shipping_address_country_code": "US"
}
```
