### ISSUE TITLE
Cannot read property 'open' of undefined

### ISSUE THREAD

**Issue by pjar** [jofftiquez/vue-stripe-checkout#24]
There are breaking changes in recent update. I guess it would be helpful to mention it in the docs. I just had to quickly downgrade to 1.0.11 to keep my app working. I'll try to create a PR with docs update.

**Comment by jofftiquez** [comment]
@pjar Im sorry about that. I will fix it now. Also, the commit message for the package.json is wrong, it should be `1.1.0` not `1.0.11` Im sorry.

**Comment by pjar** [comment]
@jofftiquez No worries, thanks for quick reaction and for a great plugin ;)

**Comment by Glenn-Domin** [comment]
Still getting this error in IE11. I'm on version 1.2.6, which appears to be the latest. It also throws `Error in mounted hook: "TypeError: Object doesn't support property or method 'append'"` when first loading the page - not sure if that's relevant.

**Comment by jofftiquez** [comment]
@Glenn-Domin I haven't tested this on any IE yet. Sorry. I'm gonna add this to my todo list.

**Comment by Propeller-SV** [comment]
I confirm @Glenn-Domin case.
`IE11`
`"vue-stripe-checkout": "^1.2.6"`
`[Vue warn]: Error in mounted hook: "TypeError: Object doesn't support property or method 'append'"`
Do you have any workaround?
Looks like the issue should be reopened.

**Comment by jofftiquez** [comment]
@Propeller-SV can you add repro via JsFiddle or Codepen? Thanks.

**Comment by Propeller-SV** [comment]
@jofftiquez this works for me in chrome but not in IE11
[https://jsbin.com/jamisif/edit?html,js,output](url)
