### ISSUE TITLE
Initialization clarification

### ISSUE THREAD

**Issue by SMen1** [jofftiquez/vue-stripe-checkout#25]
I am investigating your vue-stripe-checkout for the first time and your documentation says:

Initialization options now only accepts stripe publishable token. E.g.:

**Vue.use(VueStripeCheckout, process.env.PUBLISHABLE_TOKEN)**

searching for the implementation steps before actually installing with YARN this is the documentation:

https://vuejsfeed.com/blog/check-out-with-stripe-using-a-vue-js-plugin

with this example:

import VueStripeCheckout from 'vue-stripe-checkout'

// base/global options
// these options can be overridden 
// by the options in the .open(options) 
// function.
const options = {
  key: 'your-publishable-key',
  image: 'https://cdn.meme.am/images/100x100/15882140.jpg',
  locale: 'auto',
  currency: 'PHP',
  billingAddress: true,
  panelLabel: 'Subscribe {{amount}}'
}

**Vue.use(VueStripeCheckout, options)**

Is this article now out of date as it was posted a year ago?

For someone who is new to these implementations could you expand on process.env.PUBLISHABLE_TOKEN for implementing vue-stripe-checkout for the first time?

Apologies if this is obvious - I am new to this. Many thanks for any help you can provide.

**Comment by SebastienGras** [comment]
+1 ^^
I test to put this : PUBLISHABLE_KEY: '"pk_live_JDdzefzfzrrzvervrDDnTVFxCferetT2"'
in /config/dev.env.js and in /config/prod.env.js but it don't work :/

**Comment by jofftiquez** [comment]
Hello @SebastienGras [this link](https://vuejsfeed.com/blog/check-out-with-stripe-using-a-vue-js-plugin) is an old one, it's out of date. You should always check the official docs here on github for the latest updates. 

Regarding on your problem with `process.env. PUBLISHABLE_KEY`, `process.env` is just an environmental variable accessed by NodeJs. It's like a global variable in a computer. The reason why we want to use this is that we don't want to commit any sensitive information to our git repository. Or sometimes for the purpose of dynamicality. 

So to answer your question you just have to replace `process.env.PUBLISHABLE_KEY` with your actual publishable key. 

Like so: `Vue.use(VueStripeCheckout, 'pk_live_JDdzefzfzrrzvervrDDnTVFxCferetT2');`, it should work fine after.

**Comment by jofftiquez** [comment]
@SebastienGras kindly close the issue if you don't have any more questions 😄 Thanks for using this plugin, don't forget to leave a star if you liked it :)

**Comment by jofftiquez** [comment]
@SMen1 using process.env is one of many good practices in developing javascript applications, tho it's only optional. Maybe I'd just update the sample so that it won't cause any confusion to new users.

**Comment by SMen1** [comment]
Yes, I think adding it to your example, keeping the best practice option too (just my thought). Thank you very much indeed for replying to me so quickly - I look forward to implementing just as soon as I can.

**Comment by SMen1** [comment]
Yes! just as you have done! Making it seriously simple. :-)

**Comment by jofftiquez** [comment]
@SMen1 noice!!! 👍 

Closing this now @SebastienGras.

**Comment by SebastienGras** [comment]
Thank you for help :)
