### ISSUE TITLE
It works but : Failed to mount component: template or render function not defined.

### ISSUE THREAD

**Issue by SebastienGras** [jofftiquez/vue-stripe-checkout#26]
Sorry i'am new in vuejs and js ^^
### I have the popup with payment that works but in console i have this error :

`vue.esm.js?a026:591 [Vue warn]: Failed to mount component: template or render function not defined. found in
---> <VueStripeCheckout>
       <Stripe> at src\components\Stripe.vue
         <Shop> at src\components\Shop.vue
           <App> at src\App.vue
             <Root>`

### I have a file "Stripe.vue" with an integration of vue-stripe-checkout
![2018-11-23_20-05-34](https://user-images.githubusercontent.com/45287021/48957820-85c2d200-ef5b-11e8-90b0-b543791037d8.png)

### And a basic implementation in a "Shop.vue" :
![2018-11-23_20-08-43](https://user-images.githubusercontent.com/45287021/48957863-be62ab80-ef5b-11e8-90e4-31512ae1754e.png)

Do you have any idea why its works but i have this error ?
Thank you for the help and the package :)

**Comment by SebastienGras** [comment]
My application works anyways, and yes i use vue-cli3.
I will try to understand your link ^^

Thank you for help and rapidity !

**Comment by jofftiquez** [comment]
@SebastienGras no problem. I will try to solve this as soon as possible.

**Comment by SebastienGras** [comment]
And just by the way you forgotten an ',' in your readme before closed function :)

**Comment by jofftiquez** [comment]
Thanks! @SebastienGras
