### ISSUE TITLE
Error when passing Stripe Label option

### ISSUE THREAD

**Issue by lostlivio** [jofftiquez/vue-stripe-checkout#28]
Getting the following error in console from Stripe Component.

StripeCheckout.open: Unrecognized option 'label'. Did you mean 'name'?
You can learn about the available configuration options in the Checkout docs:
https://stripe.com/docs/checkout

**Comment by SebastienGras** [comment]
I think it's 
panelLabel: 'Payer {{amount}}'

**Comment by lostlivio** [comment]
The Stripe documents has options for both **data-label** and **data-panel-label**

**Comment by jofftiquez** [comment]
`label` refers to `data-label` will check this out. Thanks!
