### ISSUE TITLE
Cannot read property 'install' of undefined

### ISSUE THREAD

**Issue by darior87** [jofftiquez/vue-stripe-checkout#30]
with vue version `2.5.17` and vue-stripe-checkout version `1.1.3` I get `Cannot read property 'install' of undefined`

```
import VueStripeCheckout from 'vue-stripe-checkout'
console.log(VueStripeCheckout,'VueStripeCheckout') --> VueStripeCheckout is undefined
Vue.use(VueStripeCheckout, APP.stripe);
```

**Comment by johndatserakis** [comment]
Yup I got this issue too - trying to use it right now and I get `Uncaught TypeError: Cannot read property 'install' of undefined`. Standing by.

**Comment by darior87** [comment]
I solve this issue by expliciting the version. the `1.1.1` version doens't have this issue. But with that version I can't use the component inside mine. Used the same code sample as the readme

```
[Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <VueStripeCheckout>
```

**Comment by jofftiquez** [comment]
Hi @darior87 looking into this now.

**Comment by piduchesne** [comment]
Hello, same issue here.

@jofftiquez : thank you for your reactivity !

**Comment by piduchesne** [comment]
Same for me, it works. 
Thank's again

**Comment by jofftiquez** [comment]
@darior87 I hope you get a lot! Haha.
