### ISSUE TITLE
"Converting circular structure to JSON" error when opening the modal

### ISSUE THREAD

**Issue by stoykostanchev** [jofftiquez/vue-stripe-checkout#33]
When opening the modal, an error is shown in the console:

![err](https://user-images.githubusercontent.com/8082582/49089529-a6d53c80-f253-11e8-8398-c8f0e7a142c4.png)

**Comment by stoykostanchev** [comment]
This pr:

https://github.com/jofftiquez/vue-stripe-checkout/commit/3b7a6c9f516080824adbedd8a0374b26f9100376 

Changed 

 opened: () => { this.$emit('opened'); },
 closed: () => { this.$emit('closed'); }

to
 opened: () => this.$emit('opened'),
  closed: () => this.$emit('closed')

The latter returns the result of this.$emit, which is a Vue component, which then StripeCheckout tries sending a message with, tries converting to json and fails. Will shoot a PR shortly with the above reverted to the original.

**Comment by jofftiquez** [comment]
Right! Thanks @stoykostanchev
