### ISSUE TITLE
Doesn't work with multiple components

### ISSUE THREAD

**Issue by tompec** [jofftiquez/vue-stripe-checkout#35]
Hi @jofftiquez,

I tried using multiple vue-stripe-checkout on the same page and I'm having this error:
`Error in mounted hook: "ReferenceError: StripeCheckout is not defined"`

Here's an example:
https://codesandbox.io/s/mq2poqz5pj

Any idea how to fix this?

Thanks a lot!

**Comment by stoykostanchev** [comment]
The easiest thing to do is switch to using one checkout on the page and modify the properties before opening. When this component is mounted it requests the stripe bundle, and waits for it to load. However, if another checkout is mounted, it checks if the Stripe bundle is requested, but does not check if it has finished loading, just assumes it is ready and tries using it.

Alternatively, take a quick look at the code, if your use case absolutely prevents you from using this as a singleton. A workaround should not take long

**Comment by tompec** [comment]
Thanks guys. I ended up changing the properties before `.open()`. That does the trick for now 👍

**Comment by christopher4lis** [comment]
Values on the different checkouts don't change realtime. For instance, the amount only changes after you click on a open checkout button, close out, then re-open it on this CodePen: https://codesandbox.io/s/7j4kj488yx

Seems like something is throwing it out of sync.

**Comment by jofftiquez** [comment]
Thanks for the input @christopher4lis I'm still looking into this issue.

**Comment by jofftiquez** [comment]
@ABuffSeagull thank you for the input.
