### ISSUE TITLE
Pay with card not translating

### ISSUE THREAD

**Issue by superheri** [jofftiquez/vue-stripe-checkout#36]
![image](https://user-images.githubusercontent.com/30275781/49152301-5d7efe80-f2e0-11e8-8aad-786155bb15a1.png)

The component gives us the possibility to change the language, which is nice, but I would prefer if the button "Pay with card" was translated too, which is not the fact.

Please correct it to allow me to show the form in the correct language of my users.

Otherwise this plugin is super nice and easy to use, thanks to you 😎

**Comment by superheri** [comment]
Sorry just say there is a special option for this...

Thanks again for this plugin!

**Comment by jofftiquez** [comment]
@superheri all right!
