### ISSUE TITLE
Feature request - Callback if canceled

### ISSUE THREAD

**Issue by superheri** [jofftiquez/vue-stripe-checkout#39]
For my usecase of the plugin, I would need to know if the user closed the checkout window of the transaction to return sooner in my own steps.

As I see, the actual closed method is called whenever the modal is closed, even if it worked. Is it possible to have a way to know that the transaction has not been fullfilled?

Would be appreciated. And thanks again for your nice plugin.

**Comment by jofftiquez** [comment]
Hi @superheri could give me some use cases for this feature? For instance, what do you mean by "the user closed the checkout window of the transaction to return sooner" and "transaction has not been fulfilled"? Thanks :)

**Comment by superheri** [comment]
Hi, to be more precise, there is a X button on the top of the stripe checkout modal that allows the user to quit, without entering his informations. What I would need is a way to actually know if the user quits that way to show him a page with different options.

Actually we only have 3 callbacks `done`, `opened`, `closed`. Since `done` is when everything worked as expected and `closed` is called every time the modal is closed even when the user completed his payment, I would like to have a `cancelled` to allow me to act when the user cancelled and stopped everything before completing. The `closed` callback could be left as is since it may be useful for some people.

**Comment by jofftiquez** [comment]
@superheri correct me if I'm wrong so you want to have another state or event between pressing the x and before closing the dialog? 

1. Press x
2. Call canceled
3. Do you want to close this modal? Y, N, Other option.
4. If Y, close the modal
5. If N, leave the state as is. 
6. If Other, show other option without closing the modal? 

It this correct?

**Comment by jofftiquez** [comment]
@superheri I'm confused about the flow. 

Here's another question, what will the cancel event's primary purpose?

**Comment by superheri** [comment]
To call an action in my code that will change the view seen by the user.

**Comment by jofftiquez** [comment]
@superheri why don't you use the `closed` event then?

**Comment by jofftiquez** [comment]
Right. I get it now. The `closed` and `opened` events are default within stripe checkout library, adding a new one would be impossible on my end. By maybe I could modify `closed` to accommodate this feature you're requesting.
