### ISSUE TITLE
Create build for browsers

### ISSUE THREAD

**Issue by jofftiquez** [jofftiquez/vue-stripe-checkout#4]
Use rollup

**Comment by jofftiquez** [comment]
@lunafi-evan not quite. The build output of that webpack setup is for npm usage only. What we need is a version for browser. Am gonna push an update in a minute to close this. Thanks for the reminder ;)

**Comment by lunafi-evan** [comment]
got it! :+1:

**Comment by jofftiquez** [comment]
@lunafi-evan there :) Thank you for using this.
