### ISSUE TITLE
How to get decimal places to show up correctly on the right?

### ISSUE THREAD

**Issue by multidimensionalinteractive** [jofftiquez/vue-stripe-checkout#42]
I am attempting to get javascript to make the right number have a decimal point in it example 9999.99 however i cannot seem to get it to behave properly. Do you have any advice?

**Comment by multidimensionalinteractive** [comment]
For instance if i put 3.00 in the right the left pay now button displays Pay 0.03

**Comment by jofftiquez** [comment]
If you want to display `3.00` should put `300`. The value that you will put in the amount will be divided by 100.

**Comment by jofftiquez** [comment]
There's an interactive `amount` input on the demo page. You should check it out.
