### ISSUE TITLE
Multiple Stripe Checkout

### ISSUE THREAD

**Issue by pirmax** [jofftiquez/vue-stripe-checkout#43]
Hi,

I want multiple Stripe checkout on same page.

`<button @click="checkout('hobby')" class="btn btn-primary btn-block btn-sm">Pay with Stripe</button>`

I define checkout options before open Stripe modal but this is the default checkout options who opened.

```
data () {
      return {
        checkoutOptions: {
          image: '',
          name: '',
          description: '',
          currency: 'EUR',
          amount: 0
        }
      }
    },
methods: {
      async checkout (plan) {
        switch (plan) {
          case 'free':
            this.checkoutOptions.image = 'images/subscriptions/plan-free.svg';
            this.checkoutOptions.name = 'Free Plan';
            this.checkoutOptions.description = '';
            this.checkoutOptions.amount = 0;
            await this.$refs.checkoutRef.open();
            break;
          case 'hobby':
            this.checkoutOptions.image = 'images/subscriptions/plan-hobby.svg';
            this.checkoutOptions.name = 'Hobby Plan';
            this.checkoutOptions.description = '';
            this.checkoutOptions.amount = 990;
            await this.$refs.checkoutRef.open();
            break;
        }
      }
    }

```
Thanks to help me please.

**Comment by jofftiquez** [comment]
Kindly follow [this](https://github.com/jofftiquez/vue-stripe-checkout/issues/35)

**Comment by pirmax** [comment]
It's doesnt work too... Before close an issue, thanks to verify.

**Comment by jofftiquez** [comment]
That issue was tested and closed properly. It's working. Would you mind giving more information? Will re-open this for you.

**Comment by neoighodaro** [comment]
Also having the same issue

**Comment by RyanWillDev** [comment]
I was able to get around this by adding the script that is appended to the DOM when the stripe-checkout component is mounted [here](https://github.com/jofftiquez/vue-stripe-checkout/blob/master/src/index.js#L64)

By doing that I can have multiple stripe-checkout components on the page at a time.

**Comment by jofftiquez** [comment]
@ABuffSeagull as @RyanWillDev mentioned there seems to be a problem on [this line](https://github.com/jofftiquez/vue-stripe-checkout/blob/master/src/index.js#L98) which is part of your PR. Thank you. :)

**Comment by ABuffSeagull** [comment]
I'm about to head to bed, so this is just a quick thought. I'll check back in tomorrow.

I don't believe that it updates when you change the props, but if you uncomment the `updated` hook ([here](https://github.com/jofftiquez/vue-stripe-checkout/blob/master/src/index.js#L76)), it should give you the correct options when you change the props. (I know I was only talking about the key in the comment, but I guess it's for all props)

**Comment by RyanWillDev** [comment]
I played around with the code a little and created [this sandbox](https://codesandbox.io/s/llkolnkm1l) that gets multiple checkouts working without having to use the update method or swapping the checkout options.

**Comment by jofftiquez** [comment]
Oh no, I'm sorry to disturb you @ABuffSeagull.

**Comment by jofftiquez** [comment]
@RyanWillDev great I tested it out. Would you mind sending a PR so we can test and review it for this issue? Thanks.

**Comment by jofftiquez** [comment]
Irrelevant to V3, will close for now. Feel free to reopen later. Thanks.
