### ISSUE TITLE
Variable from vuex/nuxt store

### ISSUE THREAD

**Issue by Jesus82** [jofftiquez/vue-stripe-checkout#44]
Hi, I would like to use this plugin with Nuxt.js, grabbing the stripe id from the store.
Is there any way to do it? So far I've tried with this based in [this question in stackoverflow](https://stackoverflow.com/questions/45644171/adding-mutations-to-vuex-store-as-part-of-vue-plugin) with no luck

    // vue-stripe-checkout.js
    import Vue from 'vue';
    import VueStripeCheckout from 'vue-stripe-checkout';

    const options = {
      install(vue, { store }){
        if (!store) {
          throw new Error("Please provide vuex store.")
        }
        store.registerModule({states, mutations, actions })

        if (store.state.deployment.production) {
          return store.deployment.stripe_prod
        } else {
          return store.deployment.stripe_dev
        }
      }
    }

    Vue.use(VueStripeCheckout, options)

**Comment by jofftiquez** [comment]
Hello @Jesus82, I'm not a Nuxt guy but it seems to me that you are creating a custom plugin? Also, what exactly is not working here? Thank you.

**Comment by Jesus82** [comment]
Hi, thanks for the reply.

I want to have both dev and prod stripe key in the Vuex store, so if I set store.state.production = true, it will use the key stored in store.deployment.stripe_prod, and if I set store.state.production = false, it will use the key stored in store.deployment.stripe_dev

I've updated my code, but it still says "TypeError: this.options is undefined"

**Comment by jofftiquez** [comment]
Hi @Jesus82 I believe this problem has nothing to do with this plugin. Also, my knowledge in nuxt is very limited I'm not sure if I could help you. But based on your error, the `options` is not existing in the `this` context.

I'm gonna close this issue now, you can still reply for your questions tho. Thank you.
