### ISSUE TITLE
Cannot read property 'open' of undefined

### ISSUE THREAD

**Issue by stacybot123** [jofftiquez/vue-stripe-checkout#47]
Installed version is : 1.1.0 , getting error as : 

```
Cannot read property 'open' of undefined
```
Here is the function I have 

```
checkout() {
      this.$checkout.open({
        name: 'Update Card Details',
        currency: 'USD',
        amount: 0,
        token: (token) => {
            console.log(token);
        } 
      });
    }

```

**Comment by jofftiquez** [comment]
Hi @stacybot123 you are using the old version way of using checkout. Kindly check the new one from the [official github doc](https://github.com/jofftiquez/vue-stripe-checkout#sample). Thanks :)
