### ISSUE TITLE
Feature request - Add support of 3D Secure

### ISSUE THREAD

**Issue by superheri** [jofftiquez/vue-stripe-checkout#48]
Since 3D Secure is needed for some cards it would be nice that this plugin implements it.

Here is an exemple I fould about supporting 3D Secure for Stripe Checkout if it can be useful : https://jsfiddle.net/ywain/5j580jxa/

**Comment by jofftiquez** [comment]
Hi @superheri this is a nice feature. I will consider this. Thanks.

**Comment by superheri** [comment]
Just a little reminder that in September 2019, 3D Secure 2 will be required for every payments made in Europe : https://stripe.com/guides/3d-secure-2#d-secure-2-and-strong-customer-authentication

**Comment by jofftiquez** [comment]
Hi @superheri thanks for the reminder.

**Comment by jofftiquez** [comment]
@superheri do you see this feature as optional or required?

**Comment by superheri** [comment]
It is required for every card that require 3D Secure for transactions, otherwise the transactions will be refused by the card issuer. For now it is not much a problem, but it will be in September 2019 where 3D Secure will be required for every card transaction in the Europe (and I'm not talking about only one country). 

We still have 5 months before it becomes a real problem, but I was only posting a reminder to inform you about this law.

This is mentionned in the link above to Stripe documentation as well as in many other articles like this one :
"14th September 2019 - PSD2’s SCA requirements go live in Europe. Any business with substantial European volume will need to have 3D Secure 2.0 implemented by this date in order to most effectively meet SCA requirements."
https://www.adyen.com/blog/psd2-understanding-strong-customer-authentication

**Comment by faxal** [comment]
Any update on this issue or workarounds?

**Comment by jofftiquez** [comment]
Hello all, this issue is due in September 2019. I apologize, I am very busy right now. I hope I can find time to do this soon. Please be patient. Also, a PR would be much appreciated. Thanks.

**Comment by superheri** [comment]
I'm working on something, I might create a PR soon with this, so we could discuss about how to make it better because for now it's not optimal but it works.

**Comment by jofftiquez** [comment]
That would be great. Please keep me updated.

**Comment by superheri** [comment]
After research, Stripe is no more using the checkout modal. Instead, they updated their checkout window to be directly on their website. This checkout window has already the 3D Secure support and is auto updated so it will automatically support 3D Secure 2 when it will be available. This checkout window can be used in 2 ways, [Client side](https://stripe.com/docs/payments/checkout/client) or [Server side](https://stripe.com/docs/payments/checkout/server). 

- Server side is almost completely fulfilled by the server so there is no point for a Vue integration.
- Client side is still only a redirect sith some informations, like the product id of the product entered in Stripe Dashboard, that goes directly to Stripe checkout page to fulfill the transaction using a [webhook](https://stripe.com/docs/payments/checkout/fulfillment#webhooks) or something like that.

So after al that research I don't see how all this can be integrated into a Vue component since there is almost no front-end code and the most Checkout window is dealed back-end.

@jofftiquez Can you give me your thoughts on this?

**Comment by jofftiquez** [comment]
@superheri thank you for the insight. I will also research further regarding this.

**Comment by jofftiquez** [comment]
I just want to let you know that will be done very soon. Thanks.

**Comment by wpgeek922** [comment]
Hi Jofferson,

Just wanted to know have you already working on the this feature?

**Comment by jofftiquez** [comment]
Hello @wpgeek922 I am. It's currently on a local branch. I will continue working on this soon. I'm sorry I  am so busy right now. Thank you for reminding me.

**Comment by gadutime** [comment]
Hi @jofftiquez, thanks for working on this, much appreciated! Do you have any update on when can we expect this to be merged? 

Thanks a million and keep up the great work!

**Comment by jofftiquez** [comment]
Kindly refer to #64
