### ISSUE TITLE
Better testing

### ISSUE THREAD

**Issue by ABuffSeagull** [jofftiquez/vue-stripe-checkout#49]
As evidenced by [this file](https://github.com/jofftiquez/vue-stripe-checkout/blob/master/test/index.test.js), there needs to be better testing.
But since this requires downloading and parsing a script, and letting it make an iframe, I would imagine proper testing would only work inside a browser.
I'm not sure what the best test framework is for this, perhaps Karma? I've only ever used Jest, so I'm not sure.
Any ideas?

**Comment by superheri** [comment]
The only thing from my point of view that could test well the modal, since it is opened in a iframe by default by Stripe, is Selenium.

Karma is the ancestor of Jest and can't do anything UI related.

**Comment by ABuffSeagull** [comment]
Yeah, just check the modal and make sure all the info is filled in correctly.
And thanks for the info on Karma. I guess it would come down to Jest + Puppeteer or Cypress then.

**Comment by superheri** [comment]
I don't think it would be really easy to test though. Since this plugin is mostly a wrapper around a big javascript library on which we have no control.

**Comment by jofftiquez** [comment]
I've tried using Puppeteer to test this but I can't find a way to properly make it work. Same with @ABuffSeagull I am only using Jest lately so my knowledge in testing is very limited. Tho I would love to do this sometime, I just couldn't commit my time for this yet because of work. Thank you both for your inputs.

**Comment by jofftiquez** [comment]
Hello all, I merged the version 3 branch and made some fixes. Please upgrade and try the new version. Closing this now. Please create a new issue if there's any. Thank you.

IMPORTANT - there are breaking changes in the implementation, please read the documentation carefully.
