### ISSUE TITLE
Wondering how to best pass data to server. (PHP)

### ISSUE THREAD

**Issue by jordanboston** [jofftiquez/vue-stripe-checkout#5]
In the Stripe docs it shows an example of a form like so:
```
<form action="/create_subscription.php" method="POST">
  <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="pk_test_QGwMfqnkIW0ycKln03fjoWMO"
    data-image="/images/marketplace.png"
    data-name="Emma's Farm CSA"
    data-description="Subscription for 1 weekly box"
    data-amount="2000"
    data-label="Sign Me Up!">
  </script>
</form>
```

While I can get the token data and log it to the console, passing it to a PHP file from Vue seems to be giving me issues like 404 errors.  I am not sure that I can hit a PHP file, _like the example_, from the front-end since the request is likely blocked.

This is not an issue with this component, but I am wondering how to best accomplish this without just going the direction that the docs show above?  Do you happen to have any example of getting the data over to the server side?  Thanks!

**Comment by jofftiquez** [comment]
@jordanboston  I can give you an example later. :) Please wait for my response.

**Comment by jofftiquez** [comment]
@jordanboston for the meantime you can look at some of the famous REST library in Vue. There's vue-axios and vue-resource.

**Comment by jordanboston** [comment]
Thanks so much!  I am using axios, but it has dawned on me that I am going to need to create a custom endpoint on our WordPress site for this to work.  I don't think there will be any way to send the data to a PHP script on the server otherwise.

**Comment by jofftiquez** [comment]
@jordanboston  Ooooooh so you were using wordpress? I'm not very familiar with PHP stuff but for most cases you really need create an endpoint to connect to. Correct me if im wrong, so you have a wordpress website but you don't have a separate API? In that case, I don't know how but you are right, you need to create a custom endpoint. 

Also, this website that you are using `vue-stripe-checkout` with, is that a different website from the wordpress you were talking about?

**Comment by jordanboston** [comment]
It's all in the same site.  I've integrated Vue.js into the dashboard for user profiles.  It runs on the Apache PHP server, but the data is all via JSON.  I'll just create the custom endpoint, that makes sense. I had just wondered since I had seen examples of adding a form to the template area along with the token being used in the script area.

```
    <form action="create_customer.php" method="POST">

    <input type="hidden" name="stripeToken" v-model="stripeToken">
    <input type="hidden" name="stripeEmail" v-model="stripeEmail">

    <button  type="submit" class="button is-success" @click.prevent="checkout">Checkout</button>

    </form>
```
Anyway, I can close this out.  Thanks for taking the time to respond, and thanks for putting this repo together.  I realize this is not a _real issue_ and more of just a general support question so I don't want to take anymore time up.  

Cheers!

**Comment by jofftiquez** [comment]
No problem at all @jordanboston Im happy to help, thanks for the appreciation for my work. You stay awesome ok? Cheers!

**Comment by luddens** [comment]
Where do I uhhh, put the 'action' that Jordan has placed in the form, there?

In your example there is no form. But in all the Stripe docs you're supposed to include the endpoint that you're looking for in the form.

**Comment by jofftiquez** [comment]
@luddens On the example, you can do a http request to your server inside 

    token: (token) => {
      // Send the token to your server
      // for payment or subscription handling,
      // or do whatever you want with it
      // I don't really care. 
    }

**Comment by jordanboston** [comment]
@luddens Yes, you just need a server side file --which in my case was a php file, but it will depend on the framework and language you are working in.  Then I pass the data to that from the Vue component I'm using:

```
export default {
  data() {
    return {
      stripeEmail:  '',
      stripeToken:  '',
...
```

In my case I have created an endpoint for that file in the action of the form I'm hitting.

**Comment by luddens** [comment]
Sweet! I'll have to try it out later.
