### ISSUE TITLE
How to handle Stripe errors?

### ISSUE THREAD

**Issue by mrksoftware** [jofftiquez/vue-stripe-checkout#50]
Is there a way to get notified when the transaction fails so that we can react to stripe error codes?

I only see errors in the developer console but I was not able to detect them in any callback provided by VueStripeCheckout.

Thank you in advance!

**Comment by jofftiquez** [comment]
Will look into it thanks.

**Comment by jofftiquez** [comment]
Error events are now available in V3 beta. See [this](https://github.com/jofftiquez/vue-stripe-checkout/blob/61ca07de61cf2fac08d86d57c971d3ff7ca51a0b/src/Checkout.vue#L68) and [this](https://github.com/jofftiquez/vue-stripe-checkout/blob/61ca07de61cf2fac08d86d57c971d3ff7ca51a0b/src/Elements.vue#L41).
