### ISSUE TITLE
TypeError: this.$refs.checkoutRef is undefined

### ISSUE THREAD

**Issue by liboub** [jofftiquez/vue-stripe-checkout#51]
After an npm update i got that error when i try to checkout . 
That's normal ? 
How i fix that ? 
[Vue warn]: Error in v-on handler: "TypeError: this.$refs.checkoutRef is undefined"

**Comment by jofftiquez** [comment]
Hi @liboub If you transitioned from `1.1.x` to `1.2.x` there has been a breaking change. Kindly refer to the documentation.

**Comment by jofftiquez** [comment]
Kindly re-open if there are more issues. Thanks.

**Comment by liboub** [comment]
Ok i fix in my code thanks for all .
