### ISSUE TITLE
When passing in new data, component requires a second reload to load correctly

### ISSUE THREAD

**Issue by abhishekover9000** [jofftiquez/vue-stripe-checkout#52]
https://codesandbox.io/s/7j4kj488yx < click on checkout 1, then click on checkout 2 and checkout 1's data is still on there. it's not until a click out and second click of checkout 2 when the data actually loads correctly.

**Comment by jofftiquez** [comment]
I can confirm the bug. Thanks, I will look into it.

**Comment by jofftiquez** [comment]
@abhishekover9000 I can't promise to fix this soon. However, if it's fine with you, you can do this workaround. You can set a timeout of 500ms before invoking `.open()`.  See the example below.

https://codesandbox.io/s/8n10y61n52

**Comment by ABuffSeagull** [comment]
I'm not sure if there's away to do it inside the component, since the checkout needs to be opened *after* the props get updated, but probably the best fix to make sure it runs after the props get updated is to wrap it in a `Vue.$nextTick` call.
https://codesandbox.io/s/j2yzk00rv

**Comment by abhishekover9000** [comment]
Thanks all, I added the 500ms in my app for now- the nextTick is a good idea too
