### ISSUE TITLE
Provide confirmation callback

### ISSUE THREAD

**Issue by zedrdave** [jofftiquez/vue-stripe-checkout#54]
Since the $checkout mixin was removed, it doesn't seem possible to add any pre-confirmation code to the checkout button (e.g. displaying a confirm dialog warning about something).

Ideal solution would be to add a `:confirm` option that takes a callback function and cancels the checkout on `false`…

**Comment by jofftiquez** [comment]
Hi @zedrdave is this "confirmation" going to happen before opening the stripe checkout?

**Comment by zedrdave** [comment]
@jofftiquez Yes. It could be a warning about what is being purchased, for example…

**Comment by jofftiquez** [comment]
@zedrdave if so, why not just create a separate confirmation process before actually invoking `this.$refs.checkoutRef.open();`?

**Comment by jofftiquez** [comment]
1. Checkout button will call the confirmation dialog
2. If clicked "Yes" open checkout
3. Otherewise close confirmation dialog.

Something like this.

**Comment by zedrdave** [comment]
Yes, that would probably work. I hadn't realised the `checkout` function could cancel the checkout… Thanks!
