### ISSUE TITLE
CORS errors with Safari…

### ISSUE THREAD

**Issue by zedrdave** [jofftiquez/vue-stripe-checkout#55]
Any idea how to deal with the CORS errors generated when loading the Stripe frame? I noticed they even happen on the demo page:

```
Blocked a frame with origin "https://checkout.stripe.com" from accessing a frame with origin "https://jofftiquez.github.io". Protocols, domains, and ports must match.
```

**Comment by jofftiquez** [comment]
That's weird. I don't have access to Safari right now but I'll investigate this. Thanks. If it's CORS error there's a high chance that it's a server side error. Please update me when you got something new.

**Comment by jofftiquez** [comment]
Any more update @zedrdave? Will close this for now. Feel free to reopen later.
