### ISSUE TITLE
This version of Stripe's Checkout API is going into legacy mode

### ISSUE THREAD

**Issue by zedrdave** [jofftiquez/vue-stripe-checkout#56]
As I'm sure you've seen, [Stripe is planning to retire this version of their Checkout API](https://news.ycombinator.com/item?id=19739630).

The new version of Checkout is actually completely incompatible with typical SPA design (requires navigating away from the site). It might be possible to adapt the Elements API to do what the current Checkout API does, but I'm not sure yet…

Any plans to tackle this?

**Comment by jofftiquez** [comment]
Thanks for the reminder. I was bound to make a major update on the Stripe Checkout API version related to #48

**Comment by robbylucia** [comment]
Just spent quite a while trying to figure out why this plugin wasn't playing well with the other half of the work (creating a Stripe charge on the server), turns out new Stripe docs are for V3 which is not compatible with this plugin.

**Comment by jofftiquez** [comment]
#64

**Comment by robbylucia** [comment]
Thanks for the quick response, however I just wanted to update that I did get this plugin working with Stripe V3. I was foolishly passing the entire token when attempting to charge on my server, when all it needed was the token ID. (Slightly misleading error names on the Stripe side didn't help!)

**Comment by jofftiquez** [comment]
@robbylucia great! Shall we close this issue now and continue the discussion in #64 ?

**Comment by jofftiquez** [comment]
Refer to #64
