### ISSUE TITLE
How to make it work with stripe firebase cloud functions?

### ISSUE THREAD

**Issue by chiho13** [jofftiquez/vue-stripe-checkout#57]
Currently doesn't work with https://github.com/firebase/functions-samples/blob/master/stripe/functions/index.js

**Comment by jofftiquez** [comment]
@chiho13 the scope of this plugin is to tokenize the user's credit card and product. This should work properly if the implementation of any api is correct. 

Also, if you could show me the error it would be easier to help you.

**Comment by jofftiquez** [comment]
Will close for now. Kindly reopen when more details are provided.
