### ISSUE TITLE
The payments sent through this popup doesnot reflect in the Stripe account

### ISSUE THREAD

**Issue by Raman1313** [jofftiquez/vue-stripe-checkout#6]
Hi there,

I have inserted my publishable key in the code. When i fill the details and send the payment, it shows the green tick as if it has been paid successfully but it doesnot show up in my Stripe account.
Any help would be highly appreciable.

Thanks in advance.

**Comment by jofftiquez** [comment]
Hi @Raman1313 

I get that question a lot. Please be informed that Stripe's checkout is not responsible for actually storing the transaction or customer data in your stripe account. What it does is create a token from the user's card and credentials send it back to you in this function : 

```
// the sample in the README.md
...
token: (token) => {
  // handle the token
} 
...
```

When you got the token back, you can now send it to your API to be used to store customers and create payments. 

If you are using Node here's the [docs](https://stripe.com/docs/api/node#intro).

**Comment by Raman1313** [comment]
Thanks alot @jofftiquez .
