### ISSUE TITLE
unpkg.com link broken: Cannot find "/build/vue-stripe-checkout.js" in vue-stripe-checkout@3.0.0-beta

### ISSUE THREAD

**Issue by robbylucia** [jofftiquez/vue-stripe-checkout#65]
I think a new update has caused an issue with unpkg.
Using the (from the docs): https://unpkg.com/vue-stripe-checkout/build/vue-stripe-checkout.js

Causes a redirect to https://unpkg.com/vue-stripe-checkout@3.0.0-beta/build/vue-stripe-checkout.js

Which results in this error page with the following text:
Cannot find "/build/vue-stripe-checkout.js" in vue-stripe-checkout@3.0.0-beta

**Comment by jofftiquez** [comment]
Sorry it's not in npm yet. I will update this later.

**Comment by robbylucia** [comment]
Hey, I see you closed this but the link's still dead. Is this expected?

**Comment by jofftiquez** [comment]
https://unpkg.com/vue-stripe-checkout@3.0.0-beta.1/dist/index.js
