### ISSUE TITLE
normalize-component.js dependency not found

### ISSUE THREAD

**Issue by synapse709** [jofftiquez/vue-stripe-checkout#66]
Not able to get this working as I'm seeing this when I try to build the project with the Beta installed.

This dependency was not found:

* vue-runtime-helpers/dist/normalize-component.js in ./node_modules/vue-stripe-checkout/dist/index.js

**Comment by jofftiquez** [comment]
@synapse709 what version of vue are you using? 

BTW I don't recommend using the beta for production builds.

**Comment by synapse709** [comment]
Vue 3.11.0

Understood, thanks for the quick feedback.

**Comment by Apokly** [comment]
Hi,

I added `"rollup-plugin-commonjs": "^10.0.1"` on my `package.json` and run `yarn install`.
Error is still present :

```bash
ERROR  Failed to compile with 1 errors                                                                                                                                        

This dependency was not found:

* vue-runtime-helpers/dist/normalize-component.js in ./node_modules/vue-stripe-checkout/dist/index.js

To install it, you can run: npm install --save vue-runtime-helpers/dist/normalize-component.js
```

**Comment by Apokly** [comment]
> Vue 3.11.0
> 
> Understood, thanks for the quick feedback.

Vue 3.11.0 ?!

**Comment by jofftiquez** [comment]
After testing out some few "fixes" related to this issue, I decided to remove bili and use rollup again. Try `3.0.0-beta.7`
