### ISSUE TITLE
Save rollup-plugin-commonjs in package.json

### ISSUE THREAD

**Issue by jofftiquez** [jofftiquez/vue-stripe-checkout#67]
This is solved by specifying the following in package.json as a dependency, then running `npm install`:
```
    "rollup-plugin-commonjs": "^ 10.0.1",
```

_Originally posted by @seeARMS in https://github.com/jofftiquez/vue-stripe-checkout/issues/66#issuecomment-525568618_

**Comment by seeARMS** [comment]
Ref: https://github.com/egoist/bili/issues/221

**Comment by Apokly** [comment]
https://github.com/jofftiquez/vue-stripe-checkout/pull/70

**Comment by jofftiquez** [comment]
After testing out some few "fixes" related to this issue, I decided to remove bili and use rollup again. Try `3.0.0-beta.7`
