### ISSUE TITLE
Done method no longer return the token object

### ISSUE THREAD

**Issue by ianfortier** [jofftiquez/vue-stripe-checkout#68]
Weirdly, the done method doesn't return the token object anymore. 
I have the same behavior from multi projects.

"vue-stripe-checkout": "^1.2.6"

Anything I need to know :O ?

**Comment by jofftiquez** [comment]
Hi @ianfortier it's still there [see](https://github.com/jofftiquez/vue-stripe-checkout/blob/bd288da757dbdfc2e7b9fd2487cfe3e94e3b2637/src/index.js#L122). Would mind sharing any error logs or anything similar?

**Comment by jofftiquez** [comment]
Hi @ianfortier according to your code, you are not passing the `$event` object to the checkout method in the `@done` event. You can either do the following: 

`@done="checkout"` - This will implicitly pass the data to the checkout method.
`@done="checkout($event)"` - This will explicitly pass the data to the checkout method.

Kindly close the issue it this solves you problem. Thank you :)
