### ISSUE TITLE
typescript type definition file missing

### ISSUE THREAD

**Issue by HenSoftUK** [jofftiquez/vue-stripe-checkout#7]
Hi, 
could you please add typescript type definition files. I really want to use this plugin in Typescript.
Many thanks.

**Comment by jofftiquez** [comment]
@HenSoftUK I'll see what I can do.

**Comment by HenSoftUK** [comment]
Hi,
Yes, I am using typescript for Vue
Best regardsHenry 
    On Saturday, 3 February 2018, 04:07:04 GMT, Jofferson Ramirez Tiquez <notifications@github.com> wrote:  
 
 
@HenSoftUK I'll see what I can do.

**Comment by jofftiquez** [comment]
@HenSoftUK Still having the same problem in the new version? Please let me know. Thanks!

**Comment by 512dev** [comment]
@HenSoftUK I got it to work by making a new file in my project called `vue-stripe-checkout.d.ts` with a single line `declare module 'vue-stripe-checkout';`

**Comment by jofftiquez** [comment]
@512dev thanks for the input.
