### ISSUE TITLE
Update unpkg url for v3

### ISSUE THREAD

**Issue by crawfordleeds** [jofftiquez/vue-stripe-checkout#74]
I'm getting a 404 error when trying to use the unpkg cdn for >=v3 as it seems to use resources than v1.

For example, `v1.2.6` works at https://unpkg.com/vue-stripe-checkout@1.2.6/build/vue-stripe-checkout.js.

Just changing the version to 3 returns a 404 error. However, it seems to work at the following url: https://unpkg.com/vue-stripe-checkout@3.0.0-beta.11/dist/index.js.

Is this a mistake? If not, I think the README should be updated appropriately. I'm happy to make a PR.

**Comment by jofftiquez** [comment]
Hi @crawfordleeds thanks for this. Merged PR.
