### ISSUE TITLE
Error while Registering globally

### ISSUE THREAD

**Issue by 11kashifali** [jofftiquez/vue-stripe-checkout#76]
Cannot read property 'addEventListener' of null, when using
Vue.use(VueStripeCheckout, {
  publishableKey: app_key
})

on this line document.querySelector('#stripe-js').addEventListener

**Comment by fsc7** [comment]
I am having the same error

**Comment by jofftiquez** [comment]
Hello I merged the version 3 branch. I removed the global implementation for performance purposes. You can now directly import the Checkout or Element component from your consuming components. Closing this now. Please create a new issue if there's any. Thank you.
