### ISSUE TITLE
Adding meta data?

### ISSUE THREAD

**Issue by ckurir** [jofftiquez/vue-stripe-checkout#79]
Is it possible to add meta data to a charge? I like to have an "Order number" associated with the payment.

Is it possible and how to add this?

/Christian

**Comment by jofftiquez** [comment]
Hello as far I know you can add meta in the backend. I do that in my node.js implementation. Checkout their API. Thanks.

**Comment by kabaluyot** [comment]
In the case of a checkout, adding metadata is good feature just like in stripe-js

**Comment by romain130492** [comment]
no news about this?
