### ISSUE TITLE
Subscription and Plans Support

### ISSUE THREAD

**Issue by marlarius** [jofftiquez/vue-stripe-checkout#87]
1.
I believe your links for creating SKUs are wrong. Don't you mean https://stripe.com/docs/api/skus/create?

2.
SKUs cannot be used for subscriptions and plans. Is vue-stripe-checkout only meant for products with SKUs or can it also be used for plans?

**Comment by jofftiquez** [comment]
Hello @marlarius 

1. Thanks for the correction. 

2. You are correct, SKUs cannot be used for subscriptions and plans. For now, it can only handle creating one time payment using SKU and creating charges using the stripe elements. 

Will rename this issue to "Subscription and Plans Support"

**Comment by jofftiquez** [comment]
Hi, kindly check the latest demo. It includes recurring payment subscription. Thanks.

**Comment by aligajani** [comment]
@jofftiquez  How can I use the product I created on Stripe to make it work with the plugin you;ve developed please.
