### ISSUE TITLE
Uncaught (in promise) IntegrationError: SKUs for Checkout require a `name` attribute.

### ISSUE THREAD

**Issue by Felix-O** [jofftiquez/vue-stripe-checkout#89]
After following the instructions i get the console message

``` Uncaught (in promise) IntegrationError: SKUs for Checkout require a `name` attribute. ```

**Comment by jofftiquez** [comment]
@Felix-O can you send you code? Thanks.

**Comment by Felix-O** [comment]
> @Felix-O can you send you code? Thanks.

Hey, sorry about that. I will send more info next time. Also, the issue I was having was related to the stripe dashboard. I went to settings and enabled client only integration. Every product/sku I made after that works fine.

Many thanks.

**Comment by jofftiquez** [comment]
@Felix-O cool!
