### ISSUE TITLE
Using SessionId for checkout errors due

### ISSUE THREAD

**Issue by tbrown1979** [jofftiquez/vue-stripe-checkout#92]
**Describe the bug**

My checkout use-case is calling Stripe with a `sessionId`. When calling the `redirectToCheckout` method with a `sessionId` no other values can be present in the request; if using `sessionId` to redirect then only `sessionId` can be in the object. 

**To Reproduce**
1. Set up a small example where you try to use a sessionId to checkout.
2. Click on your button, it should fail, and then look at the console. You should see this:
> IntegrationError: stripe.redirectToCheckout: Do not provide other parameters when providing sessionId. Specify all parameters on your server when creating the CheckoutSession.

**Expected behavior**

I would expect that if the method of redirecting to checkout is `sessionId` that the object provided to the `redirectToCheckout` method would only include the `sessionId`. 

Am I missing something here? I'm still learning Stripe, Vue, and javascript so there's good chance I'm misundrstanding how this should work. Here's a very small example that replicates my issue. Have others been using this project to do checkouts with sessionIds? Thanks!

```vue
<template>
    <stripe-checkout
            ref="checkoutRef"
            :pk="publishableKey"
            :sessionId="sessionId"

    >
        <template slot="checkout-button">
            <button @click="checkout">Shutup and take my money!</button>
        </template>
    </stripe-checkout>
</template>

<script>
    import { StripeCheckout } from 'vue-stripe-checkout';
    export default {
        components: {
            StripeCheckout
        },
        data: () => ({
            loading: false,
            publishableKey: "pk_test_rbM3yLhvn31PWOixMsLrYUFT0065xhosZl",//process.env.PUBLISHABLE_KEY,
            sessionId: 'cs_test_MmNYSvafLSYZRrhthcGxOQUvNduAhx9MPFMvbhUUTL9iruH6sVhN70kD',
        }),
        methods: {
            checkout () {
                this.$refs.checkoutRef.redirectToCheckout();
            }
        }
    }
</script>
```

**Comment by jofftiquez** [comment]
Hello @tbrown1979 thanks for the issue. It makes sense actually. I saw your PR and I have one comment. I will do further research about `sessionId` and will let you know. TBH I haven't tested this with sessions. If you find anything useful please let me know.

**Comment by jofftiquez** [comment]
Let's continue the discussion on your PR. Thanks.
