### ISSUE TITLE
Product & Subscription

### ISSUE THREAD

**Issue by tovil** [jofftiquez/vue-stripe-checkout#94]
Hi,
Is it possible to mix plan and sku in one checkout?
When I'm trying to do so, I get an error:
`IntegrationError: Invalid stripe.redirectToCheckout parameter: items.1.sku is not an accepted parameter.`

Thanks

**Comment by jofftiquez** [comment]
Hello, @tovil I am not sure about that, I might have to review the docs first. May I see your code tho?

**Comment by tovil** [comment]
@jofftiquez 
The code is like in your example and the items array looks like:
`items: [ {sku: 'sku_xxxxxxx', quantity: 3}, {plan: 'plan_xxxxxx', quantity: 1} ]`

I've tested Stripe's redirectToCheckout code and I get the same error.
In their example for checkout subscription and add-on they use server side with stripe.checkout.sessions.create
Then they send the plan under **subscription_data** and the add-on as line items but without using sku:
```
      line_items: [
        {
          name: "Pasha e-book 1",
          quantity: 6,
          currency: "usd",
          amount: 300,
        },
      ],

```

**Comment by jofftiquez** [comment]
It says [here](git@github.com:mycurelabs/web-accounts.git): 

> The ID of the SKU that the customer would like to purchase, **OR** the ID of the plan that the customer would like to subscribe to.

Take note of the **OR**. I think it's an implicit rule to only use one plan or sku at a time. It make senses because in the checkout page for SKU and Plans have different buttons, "Buy" for SKU and "Subscribe" for Plan.

**Comment by jofftiquez** [comment]
As for the `checkout.sessions.create` this is the recommended way of doing checkout. Altho it is perfectly fine to do checkout even without creating your own session from the backend.
