### ISSUE TITLE
Create 3DS payments with Vue Stripe Elements

### ISSUE THREAD

**Issue by boghy933** [jofftiquez/vue-stripe-checkout#99]
Hello,
Is it possible to trigger the 3DS PopUp if i use Vue Stripe Elements and not the Checkout version?
Thank you.

**Comment by jofftiquez** [comment]
Hello @boghy933 that I'm not sure. As far as I know, the Stripe Element is used for server side payment. I think you can tell the server to eventually bring the user to a page where they can do the 3DS PopUp.

**Comment by boghy933** [comment]
Thank you @jofftiquez for the quick answer.
